-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.UK_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("\1050\1074\1110\1090\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> timezone",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mm", -0.6931471805599453),
                                    ("minute", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.8306181711885482, unseen = -4.574710978503383,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 95},
                   koData =
                     ClassData{prior = -0.5723107074166716,
                               unseen = -4.8283137373023015,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 123}}),
       ("integer (3..19)",
        Classifier{okData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -2.3025850929940455,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("lunch",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.19105523676270922,
                               unseen = -4.672828834461907,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day>  o'clockmorning", -3.5648268054439574),
                                    ("until <time-of-day>afternoon", -3.970291913552122),
                                    ("dayhour", -2.717528945056754),
                                    ("at <time-of-day>evening", -3.970291913552122),
                                    ("\1074\1095\1086\1088\1072evening", -3.970291913552122),
                                    ("intersect by ','evening", -3.5648268054439574),
                                    ("\1089\1100\1086\1075\1086\1076\1085\1110afternoon",
                                     -3.970291913552122),
                                    ("intersectevening", -2.178532444324067),
                                    ("hourhour", -1.2961432641255932),
                                    ("\1079\1072\1074\1090\1088\1072lunch", -3.970291913552122),
                                    ("at <time-of-day>afternoon", -3.5648268054439574),
                                    ("<time-of-day>  o'clockafternoon", -3.054001181677967),
                                    ("until <time-of-day>morning", -3.970291913552122),
                                    ("minutehour", -3.054001181677967),
                                    ("\1089\1100\1086\1075\1086\1076\1085\1110evening",
                                     -3.970291913552122),
                                    ("time-of-day (latent)morning", -3.970291913552122),
                                    ("hh:mmmorning", -3.970291913552122),
                                    ("time-of-day (latent)evening", -3.970291913552122),
                                    ("\1079\1072\1074\1090\1088\1072evening", -3.970291913552122),
                                    ("<time-of-day>  o'clockevening", -3.5648268054439574),
                                    ("hh:mmnight", -3.970291913552122),
                                    ("hh:mmafternoon", -3.970291913552122),
                                    ("at <time-of-day>morning", -3.970291913552122),
                                    ("\1063\1077\1090\1074\1077\1088morning", -3.970291913552122)],
                               n = 38},
                   koData =
                     ClassData{prior = -1.749199854809259, unseen = -3.8501476017100584,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -2.7300291078209855),
                                    ("yearhour", -2.7300291078209855),
                                    ("intersectevening", -2.4423470353692043),
                                    ("hourhour", -2.2192034840549946),
                                    ("\1055\1086\1085\1077\1076\1110\1083\1086\1082morning",
                                     -3.1354942159291497),
                                    ("year (latent)afternoon", -3.1354942159291497),
                                    ("year (latent)night", -3.1354942159291497),
                                    ("time-of-day (latent)afternoon", -3.1354942159291497),
                                    ("on <date>morning", -3.1354942159291497)],
                               n = 8}}),
       ("numbers prefix with -, minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.258096538021482,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.4462871026284195),
                                    ("decimal number", -1.0216512475319814)],
                               n = 23}}),
       ("\1087\1110\1089\1083\1103\1079\1072\1074\1090\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074\1095\1086\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16}}),
       ("\1057\1091\1073\1086\1090\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2657031657330056, unseen = -3.951243718581427,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day>  o'clock", -1.7346010553881064),
                                    ("time-of-day (latent)", -1.4469189829363254),
                                    ("hh:mm", -2.322387720290225), ("hour", -0.9360933591703348),
                                    ("minute", -2.322387720290225)],
                               n = 23},
                   koData =
                     ClassData{prior = -1.455287232606842, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.8649974374866046),
                                    ("hour", -0.8649974374866046)],
                               n = 7}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1057\1091\1073\1086\1090\1072", -2.3978952727983707),
                                    ("\1057\1077\1088\1077\1076\1072", -2.3978952727983707),
                                    ("\1053\1077\1076\1110\1083\1103", -2.3978952727983707),
                                    ("day", -0.8938178760220964),
                                    ("\1055'\1103\1090\1085\1080\1094\1103", -1.7047480922384253),
                                    ("\1055\1086\1085\1077\1076\1110\1083\1086\1082",
                                     -1.9924301646902063)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("on <date>",
        Classifier{okData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1057\1091\1073\1086\1090\1072", -2.3978952727983707),
                                    ("\1063\1077\1090\1074\1077\1088", -2.3978952727983707),
                                    ("intersect", -1.4816045409242156),
                                    ("day", -1.9924301646902063), ("hour", -1.7047480922384253),
                                    ("minute", -2.3978952727983707)],
                               n = 6},
                   koData =
                     ClassData{prior = -0.916290731874155, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time> <part-of-day>", -2.1972245773362196),
                                    ("intersect", -2.1972245773362196),
                                    ("day", -2.1972245773362196),
                                    ("\1041\1077\1088\1077\1079\1077\1085\1100",
                                     -2.1972245773362196),
                                    ("hour", -2.1972245773362196),
                                    ("\1055\1086\1085\1077\1076\1110\1083\1086\1082",
                                     -2.1972245773362196),
                                    ("month", -1.791759469228055)],
                               n = 4}}),
       ("\1074\1077\1089\1085\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("between <time-of-day> and <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -1.3862943611198906),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -1.791759469228055),
                                    ("hourhour", -1.791759469228055),
                                    ("minutehour", -1.3862943611198906)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.916290731874155, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -1.2039728043259361),
                                    ("hh:mmhh:mm", -1.2039728043259361)],
                               n = 2}}),
       ("\1063\1077\1090\1074\1077\1088",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day>  o'clock",
        Classifier{okData =
                     ClassData{prior = -0.24362208265775043,
                               unseen = -4.1588830833596715,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.9459101490553135),
                                    ("time-of-day (latent)", -1.3099213823353166),
                                    ("until <time-of-day>", -2.7568403652716422),
                                    ("hour", -0.7419373447293773),
                                    ("after <time-of-day>", -3.044522437723423)],
                               n = 29},
                   koData =
                     ClassData{prior = -1.5314763709643884,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.9650808960435872),
                                    ("hour", -0.8472978603872037),
                                    ("after <time-of-day>", -2.3513752571634776)],
                               n = 8}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -1.4350845252893227,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -0.2719337154836418, unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16}}),
       ("<ordinal> quarter",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)quarter (grain)", -0.6931471805599453),
                                    ("quarter", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)quarter (grain)", -0.6931471805599453),
                                    ("quarter", -0.6931471805599453)],
                               n = 1}}),
       ("\1057\1077\1088\1077\1076\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.2522801454008651,
                               unseen = -5.7745515455444085,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1055\1086\1085\1077\1076\1110\1083\1086\1082this <cycle>",
                                     -5.07829394257007),
                                    ("hourday", -4.162003210695915),
                                    ("hh:mm<part-of-day> of <time>", -4.162003210695915),
                                    ("dayhour", -2.2450805985138547),
                                    ("daymonth", -3.8255309740747028),
                                    ("monthyear", -3.4688560301359703),
                                    ("yearhour", -5.07829394257007),
                                    ("intersect<time-of-day>  o'clock", -4.162003210695915),
                                    ("absorption of , after named daymm/dd/yyyy",
                                     -5.07829394257007),
                                    ("<day-of-month> (ordinal)\1041\1077\1088\1077\1079\1077\1085\1100",
                                     -5.07829394257007),
                                    ("\1046\1086\1074\1090\1077\1085\1100year", -3.979681653901961),
                                    ("intersect<time> <part-of-day>", -4.162003210695915),
                                    ("\1051\1080\1089\1090\1086\1087\1072\1076year",
                                     -5.07829394257007),
                                    ("\1057\1077\1088\1077\1076\1072\1046\1086\1074\1090\1077\1085\1100",
                                     -4.672828834461907),
                                    ("intersect\1046\1086\1074\1090\1077\1085\1100",
                                     -5.07829394257007),
                                    ("intersect by ','year", -4.672828834461907),
                                    ("\1063\1077\1090\1074\1077\1088hh:mm", -5.07829394257007),
                                    ("on <date><time-of-day>  o'clock", -5.07829394257007),
                                    ("\1041\1077\1088\1077\1079\1077\1085\1100year",
                                     -5.07829394257007),
                                    ("\1057\1091\1073\1086\1090\1072<time-of-day>  o'clock",
                                     -5.07829394257007),
                                    ("mm/dd<time-of-day>  o'clock", -5.07829394257007),
                                    ("\1057\1077\1088\1077\1076\1072next <cycle>",
                                     -5.07829394257007),
                                    ("last <day-of-week> of <time>year", -5.07829394257007),
                                    ("\1042\1077\1088\1077\1089\1077\1085\1100year",
                                     -4.672828834461907),
                                    ("on <date>between <time-of-day> and <time-of-day> (interval)",
                                     -5.07829394257007),
                                    ("on <date>at <time-of-day>", -4.672828834461907),
                                    ("\1063\1077\1090\1074\1077\1088between <time-of-day> and <time-of-day> (interval)",
                                     -4.672828834461907),
                                    ("dayday", -2.9382277790737996),
                                    ("at <time-of-day>\1079\1072\1074\1090\1088\1072",
                                     -5.07829394257007),
                                    ("\1057\1091\1073\1086\1090\1072at <time-of-day>",
                                     -4.672828834461907),
                                    ("mm/ddat <time-of-day>", -4.672828834461907),
                                    ("<time> <part-of-day>between <time-of-day> and <time-of-day> (interval)",
                                     -5.07829394257007),
                                    ("<day-of-month> (ordinal)intersect", -4.385146762010125),
                                    ("hourhour", -5.07829394257007),
                                    ("hh:mmintersect by ','", -5.07829394257007),
                                    ("intersect<day-of-month> (non ordinal) <named-month>",
                                     -4.672828834461907),
                                    ("dayyear", -2.8810693652338513),
                                    ("<day-of-month> (ordinal)\1042\1110\1074\1090\1086\1088\1086\1082",
                                     -5.07829394257007),
                                    ("<day-of-month> (non ordinal) <named-month>intersect",
                                     -5.07829394257007),
                                    ("\1089\1100\1086\1075\1086\1076\1085\1110<time-of-day>  o'clock",
                                     -5.07829394257007),
                                    ("minutehour", -3.8255309740747028),
                                    ("absorption of , after named day<day-of-month> (non ordinal) <named-month>",
                                     -3.69199958145018),
                                    ("\1063\1077\1090\1074\1077\1088<part-of-day> of <time>",
                                     -5.07829394257007),
                                    ("at <time-of-day><day-of-month> (non ordinal) <named-month>",
                                     -5.07829394257007),
                                    ("hh:mm<day-of-month> (non ordinal) <named-month>",
                                     -5.07829394257007),
                                    ("\1063\1077\1090\1074\1077\1088<time-of-day> - <time-of-day> (interval)",
                                     -5.07829394257007),
                                    ("hh:mmintersect", -5.07829394257007),
                                    ("intersect by ','intersect", -5.07829394257007),
                                    ("\1042\1110\1074\1090\1086\1088\1086\1082this <cycle>",
                                     -5.07829394257007),
                                    ("dayminute", -3.5742165457937967),
                                    ("<time> <part-of-day>intersect", -5.07829394257007),
                                    ("intersectyear", -3.979681653901961),
                                    ("<ordinal> <cycle> of <time>year", -5.07829394257007),
                                    ("minuteday", -3.5742165457937967),
                                    ("absorption of , after named dayintersect",
                                     -4.162003210695915),
                                    ("\1079\1072\1074\1090\1088\1072<time-of-day>  o'clock",
                                     -5.07829394257007),
                                    ("year<time-of-day>  o'clock", -5.07829394257007),
                                    ("<time-of-day>  o'clock\1079\1072\1074\1090\1088\1072",
                                     -4.672828834461907),
                                    ("intersect by ','<time> <part-of-day>", -5.07829394257007),
                                    ("<time> <part-of-day>intersect by ','", -5.07829394257007),
                                    ("<day-of-month> (ordinal)\1057\1077\1088\1077\1076\1072",
                                     -5.07829394257007),
                                    ("mm/ddyear", -4.672828834461907),
                                    ("intersect by ','<time-of-day>  o'clock", -5.07829394257007),
                                    ("<time> <part-of-day>\1057\1091\1073\1086\1090\1072",
                                     -5.07829394257007),
                                    ("absorption of , after named daymm/dd", -5.07829394257007),
                                    ("<time> <part-of-day>absorption of , after named day",
                                     -5.07829394257007),
                                    ("intersectintersect", -4.672828834461907),
                                    ("<part-of-day> of <time><day-of-month> (non ordinal) <named-month>",
                                     -5.07829394257007),
                                    ("dayweek", -4.162003210695915),
                                    ("\1079\1072\1074\1090\1088\1072at <time-of-day>",
                                     -4.672828834461907),
                                    ("\1057\1077\1088\1077\1076\1072intersect", -5.07829394257007),
                                    ("weekyear", -4.672828834461907),
                                    ("\1063\1077\1090\1074\1077\1088<time> timezone",
                                     -4.672828834461907),
                                    ("\1089\1100\1086\1075\1086\1076\1085\1110at <time-of-day>",
                                     -4.162003210695915),
                                    ("\1089\1100\1086\1075\1086\1076\1085\1110<time> <part-of-day>",
                                     -5.07829394257007),
                                    ("\1050\1072\1090\1086\1083\1080\1094\1100\1082\1077 \1056\1110\1079\1076\1074\1086year",
                                     -5.07829394257007),
                                    ("\1057\1077\1088\1077\1076\1072this <cycle>",
                                     -5.07829394257007),
                                    ("last <cycle> of <time>year", -4.672828834461907),
                                    ("<day-of-month> (non ordinal) <named-month>year",
                                     -3.979681653901961)],
                               n = 115},
                   koData =
                     ClassData{prior = -1.500704712297635, unseen = -5.062595033026967,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -4.363098624788362),
                                    ("daymonth", -3.264486336120253),
                                    ("monthyear", -3.1103356562929947),
                                    ("yearhour", -4.363098624788362),
                                    ("intersect<time-of-day>  o'clock", -4.363098624788362),
                                    ("intersect<time> <part-of-day>", -4.363098624788362),
                                    ("absorption of , after named dayhh:mm", -4.363098624788362),
                                    ("intersect\1046\1086\1074\1090\1077\1085\1100",
                                     -4.363098624788362),
                                    ("\1063\1077\1090\1074\1077\1088hh:mm", -3.9576335166801986),
                                    ("\1041\1077\1088\1077\1079\1077\1085\1100year",
                                     -3.9576335166801986),
                                    ("\1051\1080\1087\1077\1085\1100intersect", -4.363098624788362),
                                    ("monthhour", -3.6699514442284173),
                                    ("dayday", -3.264486336120253),
                                    ("\1042\1110\1074\1090\1086\1088\1086\1082after <time-of-day>",
                                     -4.363098624788362),
                                    ("<day-of-month> (ordinal)intersect", -4.363098624788362),
                                    ("dayyear", -2.7536607123542622),
                                    ("<day-of-month> (ordinal)\1042\1110\1074\1090\1086\1088\1086\1082",
                                     -3.9576335166801986),
                                    ("\1051\1080\1087\1077\1085\1100year", -3.9576335166801986),
                                    ("dayminute", -3.6699514442284173),
                                    ("intersectyear", -3.9576335166801986),
                                    ("<day-of-month> (ordinal)\1057\1077\1088\1077\1076\1072",
                                     -4.363098624788362),
                                    ("year<time> <part-of-day>", -4.363098624788362),
                                    ("mm/ddyear", -3.264486336120253),
                                    ("on <date>year", -4.363098624788362),
                                    ("\1057\1077\1088\1077\1076\1072intersect", -4.363098624788362),
                                    ("\1053\1077\1076\1110\1083\1103intersect", -4.363098624788362),
                                    ("\1050\1074\1110\1090\1077\1085\1100year", -4.363098624788362),
                                    ("\1089\1100\1086\1075\1086\1076\1085\1110at <time-of-day>",
                                     -4.363098624788362),
                                    ("after <time-of-day>year", -4.363098624788362),
                                    ("\1056\1110\1079\1076\1074\1086 \1061\1088\1080\1089\1090\1086\1074\1077year",
                                     -4.363098624788362),
                                    ("\1053\1077\1076\1110\1083\1103on <date>",
                                     -3.9576335166801986)],
                               n = 33}}),
       ("<ordinal> <cycle> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.7047480922384253),
                                    ("ordinals (first..19th)day (grain)\1046\1086\1074\1090\1077\1085\1100",
                                     -1.7047480922384253),
                                    ("ordinals (first..19th)week (grain)\1046\1086\1074\1090\1077\1085\1100",
                                     -1.7047480922384253),
                                    ("ordinals (first..19th)week (grain)intersect",
                                     -1.7047480922384253),
                                    ("weekmonth", -1.2992829841302609)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 11},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.7047480922384253),
                                    ("month (grain)", -2.3978952727983707),
                                    ("year (grain)", -1.9924301646902063),
                                    ("week (grain)", -1.7047480922384253),
                                    ("quarter", -2.3978952727983707), ("year", -1.9924301646902063),
                                    ("month", -2.3978952727983707),
                                    ("quarter (grain)", -2.3978952727983707)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (latent)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 2}}),
       ("mm/dd/yyyy",
        Classifier{okData =
                     ClassData{prior = -1.0116009116784799, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.45198512374305727,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("<ordinal> quarter <year>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("quarteryear", -0.6931471805599453),
                                    ("ordinals (first..19th)quarter (grain)year",
                                     -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1051\1080\1087\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1050\1110\1085\1077\1094\1100 \1084\1110\1089\1103\1094\1103",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1079\1080\1084\1072",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("nth <time> of <time>",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.3862943611198906),
                                    ("dayyear", -1.8971199848858813),
                                    ("ordinals (first..19th)\1042\1110\1074\1090\1086\1088\1086\1082\1046\1086\1074\1090\1077\1085\1100",
                                     -2.3025850929940455),
                                    ("ordinals (first..19th)\1042\1110\1074\1090\1086\1088\1086\1082intersect",
                                     -2.3025850929940455),
                                    ("ordinals (first..19th)\1057\1077\1088\1077\1076\1072intersect",
                                     -1.8971199848858813),
                                    ("ordinals (first..19th)intersectyear", -1.8971199848858813)],
                               n = 6},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.252762968495368),
                                    ("ordinals (first..19th)\1057\1077\1088\1077\1076\1072\1046\1086\1074\1090\1077\1085\1100",
                                     -1.540445040947149),
                                    ("ordinals (first..19th)\1042\1110\1074\1090\1086\1088\1086\1082\1042\1077\1088\1077\1089\1077\1085\1100",
                                     -1.9459101490553135)],
                               n = 3}}),
       ("\1053\1077\1076\1110\1083\1103",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = -4.8790164169432056e-2,
                               unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -3.044522437723423, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<part-of-day> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -1.2039728043259361),
                                    ("morning<day-of-month> (non ordinal) <named-month>",
                                     -2.3025850929940455),
                                    ("hourhour", -2.3025850929940455),
                                    ("morningbetween <time-of-day> and <time-of-day> (interval)",
                                     -2.3025850929940455),
                                    ("night\1057\1091\1073\1086\1090\1072", -2.3025850929940455),
                                    ("nightabsorption of , after named day", -2.3025850929940455),
                                    ("nightintersect by ','", -2.3025850929940455),
                                    ("nightintersect", -2.3025850929940455)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)\1041\1077\1088\1077\1079\1077\1085\1100",
                                     -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1089\1100\1086\1075\1086\1076\1085\1110",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> after next",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1057\1077\1088\1077\1076\1072", -1.252762968495368),
                                    ("day", -0.8472978603872037),
                                    ("\1055'\1103\1090\1085\1080\1094\1103", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("afternoon",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.2809338454620642),
                                    ("year (grain)", -2.1972245773362196),
                                    ("week (grain)", -1.2809338454620642),
                                    ("quarter", -2.1972245773362196), ("year", -2.1972245773362196),
                                    ("quarter (grain)", -2.1972245773362196)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1053\1086\1074\1080\1081 \1088\1110\1082",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("\1079\1072\1074\1090\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.5260930958967791,
                               unseen = -3.4011973816621555,
                               likelihoods =
                                 HashMap.fromList [("integer (numeric)", -7.145896398214498e-2)],
                               n = 26},
                   koData =
                     ClassData{prior = -0.8938178760220964,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.3364722366212129),
                                    ("integer (3..19)", -1.6582280766035324),
                                    ("integer 2", -2.3513752571634776)],
                               n = 18}}),
       ("year",
        Classifier{okData =
                     ClassData{prior = -0.24512245803298496,
                               unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 18},
                   koData =
                     ClassData{prior = -1.5260563034950494,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 5}}),
       ("last <day-of-week> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -0.916290731874155),
                                    ("\1055\1086\1085\1077\1076\1110\1083\1086\1082\1041\1077\1088\1077\1079\1077\1085\1100",
                                     -1.6094379124341003),
                                    ("\1053\1077\1076\1110\1083\1103\1041\1077\1088\1077\1079\1077\1085\1100",
                                     -1.6094379124341003),
                                    ("\1053\1077\1076\1110\1083\1103intersect",
                                     -1.6094379124341003)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -1.1631508098056809, unseen = -4.23410650459726,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.6100697927420065),
                                    ("integer 2week (grain)", -3.5263605246161616),
                                    ("integer (numeric)day (grain)", -2.833213344056216),
                                    ("second", -3.5263605246161616),
                                    ("integer 2hour (grain)", -3.5263605246161616),
                                    ("integer (numeric)second (grain)", -3.5263605246161616),
                                    ("integer (numeric)year (grain)", -3.120895416507997),
                                    ("day", -2.833213344056216), ("year", -2.833213344056216),
                                    ("integer (3..19)week (grain)", -3.5263605246161616),
                                    ("integer (numeric)week (grain)", -3.120895416507997),
                                    ("hour", -2.833213344056216), ("month", -3.5263605246161616),
                                    ("integer (numeric)minute (grain)", -2.4277482359480516),
                                    ("integer (3..19)month (grain)", -3.5263605246161616),
                                    ("minute", -2.4277482359480516),
                                    ("integer (numeric)hour (grain)", -3.120895416507997),
                                    ("integer 2year (grain)", -3.5263605246161616)],
                               n = 20},
                   koData =
                     ClassData{prior = -0.3746934494414107, unseen = -4.762173934797756,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.9618307218783095),
                                    ("integer 2week (grain)", -4.060443010546419),
                                    ("integer (numeric)day (grain)", -3.367295829986474),
                                    ("integer (3..19)day (grain)", -4.060443010546419),
                                    ("integer 2minute (grain)", -4.060443010546419),
                                    ("second", -3.144152278672264),
                                    ("integer 2month (grain)", -4.060443010546419),
                                    ("integer (3..19)second (grain)", -4.060443010546419),
                                    ("integer (numeric)second (grain)", -3.654977902438255),
                                    ("integer (numeric)year (grain)", -3.654977902438255),
                                    ("integer (3..19)year (grain)", -4.060443010546419),
                                    ("day", -2.9618307218783095), ("year", -3.144152278672264),
                                    ("integer (3..19)week (grain)", -4.060443010546419),
                                    ("integer 2day (grain)", -4.060443010546419),
                                    ("integer (numeric)week (grain)", -3.367295829986474),
                                    ("integer (3..19)minute (grain)", -4.060443010546419),
                                    ("hour", -1.8091512119399242), ("month", -3.144152278672264),
                                    ("integer (numeric)minute (grain)", -3.654977902438255),
                                    ("integer (3..19)month (grain)", -4.060443010546419),
                                    ("integer (numeric)month (grain)", -3.654977902438255),
                                    ("integer (3..19)hour (grain)", -4.060443010546419),
                                    ("integer 2second (grain)", -4.060443010546419),
                                    ("minute", -3.144152278672264),
                                    ("integer (numeric)hour (grain)", -1.8632184332102),
                                    ("integer 2year (grain)", -4.060443010546419)],
                               n = 44}}),
       ("ordinals (first..19th)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1042\1077\1088\1077\1089\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> after <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("yearday", -0.6931471805599453),
                                    ("<integer> <unit-of-duration>\1056\1110\1079\1076\1074\1086 \1061\1088\1080\1089\1090\1086\1074\1077",
                                     -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1041\1077\1088\1077\1079\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1051\1102\1090\1080\1081",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd.(mm.)? - dd.mm.(yy[yy]?)? (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -0.6523251860396901, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -0.7357067949787413,
                               unseen = -3.2188758248682006,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 23}}),
       ("intersect by ','",
        Classifier{okData =
                     ClassData{prior = -6.0624621816434854e-2,
                               unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -3.1780538303479458),
                                    ("dayhour", -2.772588722239781),
                                    ("\1055'\1103\1090\1085\1080\1094\1103mm/dd",
                                     -3.1780538303479458),
                                    ("\1055'\1103\1090\1085\1080\1094\1103intersect",
                                     -2.2617630984737906),
                                    ("dayday", -1.3862943611198906),
                                    ("\1057\1077\1088\1077\1076\1072<day-of-month> (non ordinal) <named-month>",
                                     -3.1780538303479458),
                                    ("intersect<day-of-month> (non ordinal) <named-month>",
                                     -2.772588722239781),
                                    ("\1055\1086\1085\1077\1076\1110\1083\1086\1082<day-of-month> (non ordinal) <named-month>",
                                     -2.772588722239781),
                                    ("\1057\1091\1073\1086\1090\1072<day-of-month> (non ordinal) <named-month>",
                                     -3.1780538303479458),
                                    ("minuteday", -2.772588722239781),
                                    ("\1055'\1103\1090\1085\1080\1094\1103mm/dd/yyyy",
                                     -3.1780538303479458),
                                    ("<part-of-day> of <time><day-of-month> (non ordinal) <named-month>",
                                     -3.1780538303479458),
                                    ("\1053\1077\1076\1110\1083\1103<day-of-month> (non ordinal) <named-month>",
                                     -3.1780538303479458),
                                    ("\1055'\1103\1090\1085\1080\1094\1103<day-of-month> (non ordinal) <named-month>",
                                     -2.772588722239781)],
                               n = 16},
                   koData =
                     ClassData{prior = -2.833213344056216, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1055'\1103\1090\1085\1080\1094\1103hh:mm",
                                     -2.1972245773362196),
                                    ("dayminute", -2.1972245773362196)],
                               n = 1}}),
       ("second (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect by 'of', 'from', 's",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayweek", -0.6931471805599453),
                                    ("\1053\1077\1076\1110\1083\1103last <cycle>",
                                     -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.55814461804655), ("day", -1.845826690498331),
                                    ("year", -2.2512917986064953),
                                    ("<integer> <unit-of-duration>", -0.8649974374866046),
                                    ("month", -2.2512917986064953)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1051\1080\1089\1090\1086\1087\1072\1076",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1053\1077\1076\1110\1083\1103", -1.0986122886681098),
                                    ("day", -0.8109302162163288),
                                    ("\1042\1110\1074\1090\1086\1088\1086\1082",
                                     -1.5040773967762742)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -1.2039728043259361,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 7}}),
       ("\1055'\1103\1090\1085\1080\1094\1103",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time> <part-of-day>", -2.1972245773362196),
                                    ("<time-of-day>  o'clock", -1.9095425048844386),
                                    ("\1050\1110\1085\1077\1094\1100 \1084\1110\1089\1103\1094\1103",
                                     -2.6026896854443837),
                                    ("time-of-day (latent)", -1.9095425048844386),
                                    ("hour", -1.0986122886681098), ("month", -2.6026896854443837)],
                               n = 9},
                   koData =
                     ClassData{prior = -1.3862943611198906, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mm", -1.6094379124341003), ("hour", -2.0149030205422647),
                                    ("midnight|EOD|end of day", -2.0149030205422647),
                                    ("minute", -1.6094379124341003)],
                               n = 3}}),
       ("\1046\1086\1074\1090\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.6109179126442243,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 35}}),
       ("\1055\1086\1085\1077\1076\1110\1083\1086\1082",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.8472978603872037,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("midnight|EOD|end of day",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("month (grain)", -2.0794415416798357),
                                    ("year (grain)", -2.0794415416798357),
                                    ("week (grain)", -1.3862943611198906),
                                    ("year", -2.0794415416798357), ("month", -2.0794415416798357)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.912023005428146,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.793208009442517),
                                    ("integer (numeric)day (grain)", -3.1986731175506815),
                                    ("integer (3..19)day (grain)", -3.1986731175506815),
                                    ("second", -2.793208009442517),
                                    ("integer (3..19)second (grain)", -3.1986731175506815),
                                    ("integer (numeric)second (grain)", -3.1986731175506815),
                                    ("integer (numeric)year (grain)", -3.1986731175506815),
                                    ("integer (3..19)year (grain)", -3.1986731175506815),
                                    ("day", -2.793208009442517), ("year", -2.793208009442517),
                                    ("integer (3..19)week (grain)", -3.1986731175506815),
                                    ("integer (numeric)week (grain)", -3.1986731175506815),
                                    ("integer (3..19)minute (grain)", -3.1986731175506815),
                                    ("hour", -2.793208009442517), ("month", -2.793208009442517),
                                    ("integer (numeric)minute (grain)", -3.1986731175506815),
                                    ("integer (3..19)month (grain)", -3.1986731175506815),
                                    ("integer (numeric)month (grain)", -3.1986731175506815),
                                    ("integer (3..19)hour (grain)", -3.1986731175506815),
                                    ("minute", -2.793208009442517),
                                    ("integer (numeric)hour (grain)", -3.1986731175506815)],
                               n = 14},
                   koData =
                     ClassData{prior = -infinity, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("in <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4657359027997265,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.740840023925201), ("second", -2.740840023925201),
                                    ("day", -2.740840023925201), ("year", -2.740840023925201),
                                    ("<integer> <unit-of-duration>", -0.8690378470236094),
                                    ("hour", -2.0476928433652555), ("minute", -1.6422277352570913)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<datetime> - <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.6190392084062235, unseen = -3.258096538021482,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersecthh:mm", -2.5257286443082556),
                                    ("minuteminute", -1.6094379124341003),
                                    ("hh:mmhh:mm", -1.8325814637483102),
                                    ("dayday", -1.8325814637483102),
                                    ("<day-of-month> (non ordinal) <named-month><day-of-month> (non ordinal) <named-month>",
                                     -2.120263536200091),
                                    ("mm/ddmm/dd", -2.5257286443082556)],
                               n = 7},
                   koData =
                     ClassData{prior = -0.7731898882334817,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -2.03688192726104),
                                    ("mm/ddhh:mm", -2.03688192726104),
                                    ("minuteminute", -2.4423470353692043),
                                    ("hh:mmhh:mm", -2.4423470353692043),
                                    ("dayday", -2.4423470353692043),
                                    ("dayminute", -2.03688192726104),
                                    ("\1057\1077\1088\1087\1077\1085\1100<day-of-month> (non ordinal) <named-month>",
                                     -2.4423470353692043),
                                    ("mm/ddmm/dd", -2.4423470353692043),
                                    ("\1051\1080\1087\1077\1085\1100<day-of-month> (non ordinal) <named-month>",
                                     -2.4423470353692043)],
                               n = 6}}),
       ("<time-of-day> - <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.45198512374305727,
                               unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -1.6094379124341003),
                                    ("minuteminute", -1.3862943611198906),
                                    ("hh:mmhh:mm", -1.3862943611198906),
                                    ("minutehour", -1.6094379124341003)],
                               n = 7},
                   koData =
                     ClassData{prior = -1.0116009116784799, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -1.9459101490553135),
                                    ("minuteminute", -1.9459101490553135),
                                    ("hh:mmhh:mm", -1.9459101490553135),
                                    ("hourminute", -1.540445040947149),
                                    ("minutehour", -1.9459101490553135),
                                    ("time-of-day (latent)hh:mm", -1.540445040947149)],
                               n = 4}}),
       ("\1057\1077\1088\1087\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.7612001156935624,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.639057329615259),
                                    ("integer 2week (grain)", -3.044522437723423),
                                    ("integer (numeric)day (grain)", -3.044522437723423),
                                    ("integer 2minute (grain)", -3.044522437723423),
                                    ("second", -2.639057329615259),
                                    ("integer 2month (grain)", -3.044522437723423),
                                    ("integer (numeric)second (grain)", -3.044522437723423),
                                    ("integer (numeric)year (grain)", -3.044522437723423),
                                    ("day", -2.639057329615259), ("year", -2.639057329615259),
                                    ("integer 2day (grain)", -3.044522437723423),
                                    ("integer (numeric)week (grain)", -3.044522437723423),
                                    ("month", -2.639057329615259),
                                    ("integer (numeric)minute (grain)", -3.044522437723423),
                                    ("integer (numeric)month (grain)", -3.044522437723423),
                                    ("integer 2second (grain)", -3.044522437723423),
                                    ("minute", -2.639057329615259),
                                    ("integer 2year (grain)", -3.044522437723423)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("nth <time> after <time>",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayday", -0.916290731874155),
                                    ("ordinals (first..19th)\1042\1110\1074\1090\1086\1088\1086\1082intersect",
                                     -0.916290731874155)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayday", -0.916290731874155),
                                    ("ordinals (first..19th)\1042\1110\1074\1090\1086\1088\1086\1082\1050\1072\1090\1086\1083\1080\1094\1100\1082\1077 \1056\1110\1079\1076\1074\1086",
                                     -0.916290731874155)],
                               n = 1}}),
       ("\1056\1110\1079\1076\1074\1086 \1061\1088\1080\1089\1090\1086\1074\1077",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("<day-of-month> (non ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = -8.338160893905101e-2,
                               unseen = -3.9889840465642745,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)\1051\1080\1087\1077\1085\1100",
                                     -2.3608540011180215),
                                    ("integer (numeric)\1050\1074\1110\1090\1077\1085\1100",
                                     -3.2771447329921766),
                                    ("integer (numeric)\1041\1077\1088\1077\1079\1077\1085\1100",
                                     -2.3608540011180215),
                                    ("integer (numeric)\1051\1102\1090\1080\1081",
                                     -1.7730673362159024),
                                    ("integer (numeric)\1057\1077\1088\1087\1077\1085\1100",
                                     -2.3608540011180215),
                                    ("month", -0.7922380832041762),
                                    ("integer (numeric)\1042\1077\1088\1077\1089\1077\1085\1100",
                                     -2.871679624884012)],
                               n = 23},
                   koData =
                     ClassData{prior = -2.5257286443082556,
                               unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)\1051\1080\1087\1077\1085\1100",
                                     -1.2992829841302609),
                                    ("month", -1.2992829841302609)],
                               n = 2}}),
       ("this|next <day-of-week>",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1057\1077\1088\1077\1076\1072", -1.3862943611198906),
                                    ("day", -0.9808292530117262),
                                    ("\1042\1110\1074\1090\1086\1088\1086\1082",
                                     -1.3862943611198906)],
                               n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -1.0986122886681098),
                                    ("\1055\1086\1085\1077\1076\1110\1083\1086\1082",
                                     -1.0986122886681098)],
                               n = 1}}),
       ("quarter (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <cycle> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.540445040947149),
                                    ("day (grain)intersect", -1.9459101490553135),
                                    ("day (grain)\1046\1086\1074\1090\1077\1085\1100",
                                     -1.9459101490553135),
                                    ("weekmonth", -1.540445040947149),
                                    ("week (grain)intersect", -1.9459101490553135),
                                    ("week (grain)\1042\1077\1088\1077\1089\1077\1085\1100",
                                     -1.9459101490553135)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = -0.1823215567939546,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -1.791759469228055, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1042\1110\1074\1090\1086\1088\1086\1082",
        Classifier{okData =
                     ClassData{prior = -0.15415067982725836,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -1.9459101490553135,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("after <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.8109302162163288, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day>  o'clock", -1.6094379124341003),
                                    ("time-of-day (latent)", -1.6094379124341003),
                                    ("hour", -1.0986122886681098)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.587786664902119, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day>  o'clock", -2.1400661634962708),
                                    ("intersect", -2.1400661634962708),
                                    ("day", -1.4469189829363254),
                                    ("time-of-day (latent)", -2.1400661634962708),
                                    ("hour", -1.7346010553881064),
                                    ("\1056\1110\1079\1076\1074\1086 \1061\1088\1080\1089\1090\1086\1074\1077",
                                     -2.1400661634962708),
                                    ("\1050\1072\1090\1086\1083\1080\1094\1100\1082\1077 \1056\1110\1079\1076\1074\1086",
                                     -2.1400661634962708)],
                               n = 5}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -2.3025850929940455,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<month> dd-dd (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1051\1080\1087\1077\1085\1100", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1083\1110\1090\1086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1079\1072\1074\1095\1086\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1050\1072\1090\1086\1083\1080\1094\1100\1082\1077 \1056\1110\1079\1076\1074\1086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1074\1077\1089\1085\1072", -1.791759469228055),
                                    ("day", -1.3862943611198906), ("hour", -1.791759469228055),
                                    ("week-end", -1.791759469228055),
                                    ("\1083\1110\1090\1086", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1079\1080\1084\1072", -1.3862943611198906),
                                    ("day", -1.3862943611198906)],
                               n = 1}})]