-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.ZH_MO (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("relative minutes to|till|before <integer> (hour-of-day) with minute unit",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (numeric)",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> timezone",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> am|pm", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Thursday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.17606315460553215,
                               unseen = -5.241747015059643,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 187},
                   koData =
                     ClassData{prior = -1.8236528330040087,
                               unseen = -3.6375861597263857,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 36}}),
       ("the day before yesterday",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\22269\38469\28040\36153\32773\26435\30410\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24314\20891\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next next year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453), ("Sunday", -0.6931471805599453)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tonight",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = -1.455287232606842, unseen = -3.4011973816621555,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 28},
                   koData =
                     ClassData{prior = -0.2657031657330056, unseen = -4.543294782270004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 92}}),
       ("<time-of-day> o'clock",
        Classifier{okData =
                     ClassData{prior = -0.5625269981428811, unseen = -4.61512051684126,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 49},
                   koData =
                     ClassData{prior = -0.8434293836092833, unseen = -4.343805421853684,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 37}}),
       ("national day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("number suffix: \21313",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 47},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20803\26086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.11492996667397698,
                               unseen = -7.403061091090091,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -5.793013608384143),
                                    ("dayhour", -2.2319675257800924),
                                    ("last last year<named-month> <day-of-month>",
                                     -6.709304340258298),
                                    ("daymonth", -5.3230099791384085),
                                    ("<named-month> <day-of-month><part-of-day> <dim time>",
                                     -4.106614654813915),
                                    ("monthday", -2.4120189340395077),
                                    ("this yearmonth (numeric with month symbol)",
                                     -6.016157159698354),
                                    ("yearhour", -3.4321596072661222),
                                    ("this <cycle><named-month> <day-of-month>",
                                     -6.016157159698354),
                                    ("last <cycle><day-of-month>", -6.303839232150135),
                                    ("<dim time> <part-of-day>half after|past <integer> (hour-of-day)",
                                     -6.303839232150135),
                                    ("this <cycle>month (numeric with month symbol)",
                                     -6.016157159698354),
                                    ("todayrelative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -5.793013608384143),
                                    ("last last yearintersect", -4.8375021633567075),
                                    ("intersect by \",\"<day-of-month>", -4.694401319716034),
                                    ("next yearintersect", -4.8375021633567075),
                                    ("<dim time> <part-of-day>quarter after|past <integer> (hour-of-day)",
                                     -6.303839232150135),
                                    ("<day-of-month><time-of-day> o'clock", -4.357929083094821),
                                    ("year (numeric with year symbol)<named-month> <day-of-month>",
                                     -4.357929083094821),
                                    ("<dim time> <part-of-day><time-of-day> o'clock",
                                     -3.3420085102718247),
                                    ("<day-of-month><part-of-day> <dim time>", -3.968464316333098),
                                    ("monthhour", -2.7111036385891003),
                                    ("last last year<dim time> <part-of-day>", -6.303839232150135),
                                    ("year (numeric with year symbol)month (numeric with month symbol)",
                                     -4.4580125416518035),
                                    ("dayday", -3.359400252983694),
                                    ("todayrelative minutes after|past <integer> (hour-of-day)",
                                     -5.45654137176293),
                                    ("hourhour", -2.8485746292177034),
                                    ("this <cycle><day-of-month>", -6.016157159698354),
                                    ("this <cycle><part-of-day> <dim time>", -5.205226943482025),
                                    ("last yearmonth (numeric with month symbol)",
                                     -6.709304340258298),
                                    ("this <time><time-of-day> o'clock", -5.793013608384143),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day)",
                                     -5.45654137176293),
                                    ("<dim time> <part-of-day>three quarter after|past <integer> (hour-of-day)",
                                     -6.303839232150135),
                                    ("this <cycle><time-of-day> o'clock", -6.303839232150135),
                                    ("last year<named-month> <day-of-month>", -6.709304340258298),
                                    ("the day after the day after tomorrow<part-of-day> <dim time>",
                                     -5.793013608384143),
                                    ("hourminute", -4.569238176762028),
                                    ("next yearmonth (numeric with month symbol)",
                                     -6.709304340258298),
                                    ("absorption of , after named daymonth (numeric with month symbol)",
                                     -5.3230099791384085),
                                    ("next next yearmonth (numeric with month symbol)",
                                     -6.709304340258298),
                                    ("month (numeric with month symbol)<day-of-month>",
                                     -2.6839526495231496),
                                    ("<named-month> <day-of-month><time-of-day> o'clock",
                                     -4.4580125416518035),
                                    ("<dim time> <part-of-day>relative minutes to|till|before <integer> (hour-of-day)",
                                     -6.303839232150135),
                                    ("month (numeric with month symbol)<dim time> <part-of-day>",
                                     -3.8189325823621343),
                                    ("next next year<named-month> <day-of-month>",
                                     -6.709304340258298),
                                    ("absorption of , after named day<named-month> <day-of-month>",
                                     -4.694401319716034),
                                    ("this yearintersect", -6.016157159698354),
                                    ("next year<dim time> <part-of-day>", -6.303839232150135),
                                    ("intersect<time-of-day> o'clock", -3.531250509910353),
                                    ("yearmonth", -4.03515569083177),
                                    ("intersect<dim time> <part-of-day>", -5.793013608384143),
                                    ("this year<named-month> <day-of-month>", -6.016157159698354),
                                    ("next next yearintersect", -4.8375021633567075),
                                    ("intersect<day-of-month>", -3.595789031047924),
                                    ("dayminute", -3.7388898746885975),
                                    ("intersect<part-of-day> <dim time>", -3.4706258880939185),
                                    ("last year<dim time> <part-of-day>", -6.303839232150135),
                                    ("todayhalf after|past <integer> (hour-of-day)",
                                     -6.709304340258298),
                                    ("absorption of , after named dayintersect",
                                     -4.694401319716034),
                                    ("today<time-of-day> o'clock", -6.303839232150135),
                                    ("tonight<time-of-day> o'clock", -5.793013608384143),
                                    ("last yearintersect", -4.8375021633567075),
                                    ("next next year<dim time> <part-of-day>", -6.303839232150135),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -5.205226943482025),
                                    ("intersectintersect", -4.8375021633567075),
                                    ("today<part-of-day> <dim time>", -5.205226943482025),
                                    ("the day after the day after tomorrow<time-of-day> o'clock",
                                     -6.709304340258298),
                                    ("year (numeric with year symbol)intersect",
                                     -4.357929083094821),
                                    ("yearday", -3.291577656644933),
                                    ("next year<named-month> <day-of-month>", -6.709304340258298),
                                    ("month (numeric with month symbol)intersect",
                                     -3.3420085102718247),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -5.793013608384143),
                                    ("this <cycle>half after|past <integer> (hour-of-day)",
                                     -6.709304340258298),
                                    ("this <cycle>intersect", -6.016157159698354),
                                    ("last last yearmonth (numeric with month symbol)",
                                     -6.709304340258298)],
                               n = 780},
                   koData =
                     ClassData{prior = -2.2203469947570738, unseen = -5.602118820879701,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -3.4011973816621555),
                                    ("dayhour", -1.666596326274049),
                                    ("monthday", -4.90527477843843),
                                    ("the day after tomorrow<part-of-day> <dim time>",
                                     -3.9889840465642745),
                                    ("month (numeric with month symbol)next n <cycle>",
                                     -4.90527477843843),
                                    ("<day-of-month><time-of-day> o'clock", -3.8066624897703196),
                                    ("<dim time> <part-of-day><time-of-day> o'clock",
                                     -2.765208614942159),
                                    ("todayrelative minutes after|past <integer> (hour-of-day)",
                                     -3.8066624897703196),
                                    ("hourhour", -2.765208614942159),
                                    ("this <cycle><part-of-day> <dim time>", -2.890371757896165),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day)",
                                     -3.8066624897703196),
                                    ("this <cycle><dim time> <part-of-day>", -4.499809670330265),
                                    ("this <cycle><time-of-day> o'clock", -3.6525118099430616),
                                    ("hourminute", -3.4011973816621555),
                                    ("weekhour", -4.499809670330265),
                                    ("dayminute", -2.6539829798319343),
                                    ("the day after tomorrow<time-of-day> o'clock",
                                     -4.90527477843843),
                                    ("today<time-of-day> o'clock", -3.6525118099430616),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -3.4011973816621555),
                                    ("today<part-of-day> <dim time>", -2.890371757896165)],
                               n = 95}}),
       ("half after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("early morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.7884573603642702, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -0.6061358035703156, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18}}),
       ("Saturday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.7472144018302211,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("month (grain)", -1.791759469228055),
                                    ("year (grain)", -2.4849066497880004),
                                    ("week (grain)", -1.3862943611198906),
                                    ("year", -2.4849066497880004), ("month", -1.791759469228055)],
                               n = 9},
                   koData =
                     ClassData{prior = -0.6418538861723948, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.8602012652231115),
                                    ("week (grain)", -0.8602012652231115)],
                               n = 10}}),
       ("last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.127134385045092,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.031432322493475),
                                    ("Monday", -2.031432322493475), ("Friday", -2.501435951739211),
                                    ("day", -0.7435780341868373), ("Tuesday", -1.7129785913749407)],
                               n = 28},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes after|past <integer> (hour-of-day) with minute unit",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -2.4849066497880004),
                                    ("<integer> (latent time-of-day)integer with consecutive unit modifiers",
                                     -1.2321436812926323),
                                    ("<integer> (latent time-of-day)integer (numeric)",
                                     -1.791759469228055),
                                    ("hour", -0.7801585575495751)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd/yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening|night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.258096538021482,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 24},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day before the day before yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes to|till|before <integer> (hour-of-day) with minute unit reversed",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)<integer> (latent time-of-day)",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm (time-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> (latent time-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.46134556650262093,
                               unseen = -4.5217885770490405,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.5596157879354228),
                                    ("integer with consecutive unit modifiers", -3.41224721784874),
                                    ("integer (0..10)", -0.9555114450274363)],
                               n = 87},
                   koData =
                     ClassData{prior = -0.995428052432879, unseen = -4.02535169073515,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -2.3978952727983707),
                                    ("integer (0..10)", -0.29376111852816306),
                                    ("<number>\20010/\20491", -1.927891643552635)],
                               n = 51}}),
       ("nth <time> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -0.6931471805599453),
                                    ("month (numeric with month symbol)ordinal (digits)Monday",
                                     -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (numeric with month symbol)",
        Classifier{okData =
                     ClassData{prior = -0.16303962724450435, unseen = -4.61512051684126,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.7985076962177716),
                                    ("number suffix: \21313", -2.995732273553991),
                                    ("integer (0..10)", -0.7133498878774648)],
                               n = 96},
                   koData =
                     ClassData{prior = -1.8941744746561244,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (0..10)", -1.9459101490553135),
                                    ("<number>\20010/\20491", -0.2719337154836418)],
                               n = 17}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = -0.9216815805090316,
                               unseen = -3.6635616461296463,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 37},
                   koData =
                     ClassData{prior = -0.5072478024181066, unseen = -4.060443010546419,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 56}}),
       ("year (numeric with year symbol)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24858\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day after the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, negative or minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 4}}),
       ("Friday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("three quarter after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\28595\38376\22238\24402\32426\24565\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("fractional number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8}}),
       ("Sunday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("afternoon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> from now",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.5819215454497209, unseen = -4.442651256490317,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.9459101490553135),
                                    ("month (grain)", -3.044522437723423),
                                    ("year (grain)", -2.4849066497880004),
                                    ("week (grain)", -1.9459101490553135),
                                    ("day", -1.486377819676873), ("year", -2.4849066497880004),
                                    ("month", -3.044522437723423),
                                    ("day (grain)", -1.486377819676873)],
                               n = 38},
                   koData =
                     ClassData{prior = -0.8183103235139514, unseen = -4.23410650459726,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.7855205006909605),
                                    ("week (grain)", -0.7855205006909605)],
                               n = 30}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -0.48550781578170077,
                               unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16},
                   koData =
                     ClassData{prior = -0.9555114450274363,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10}}),
       ("<dim time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -9.121600827166168e-2,
                               unseen = -5.996452088619021,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.8065756214658142),
                                    ("this <time>early morning", -5.300814246746624),
                                    ("<day-of-month>evening|night", -3.6913763343125234),
                                    ("<day-of-month>noon", -4.6076670661866785),
                                    ("national dayevening|night", -4.895349138638459),
                                    ("<day-of-month>early morning", -4.202201958078514),
                                    ("the day after the day after tomorrowafternoon",
                                     -5.300814246746624),
                                    ("<named-month> <day-of-month>morning", -2.9494389895831463),
                                    ("Fridayafternoon", -4.895349138638459),
                                    ("<named-month> <day-of-month>noon", -4.895349138638459),
                                    ("<named-month> <day-of-month>evening|night",
                                     -4.048051278251256),
                                    ("intersectafternoon", -4.384523514872469),
                                    ("this <time>evening|night", -5.300814246746624),
                                    ("\24773\20154\33410evening|night", -4.895349138638459),
                                    ("<day-of-month>morning", -2.8584672113774197),
                                    ("this <day-of-week>afternoon", -5.300814246746624),
                                    ("this <time>noon", -5.300814246746624),
                                    ("Fridayearly morning", -4.895349138638459),
                                    ("Fridaymorning", -4.895349138638459),
                                    ("the day after the day after tomorrowmorning",
                                     -4.895349138638459),
                                    ("\20799\31461\33410afternoon", -4.895349138638459),
                                    ("<named-month> <day-of-month>afternoon", -4.384523514872469),
                                    ("this <cycle>morning", -3.914519885626733),
                                    ("todayearly morning", -5.300814246746624),
                                    ("intersectevening|night", -4.048051278251256),
                                    ("this <day-of-week>noon", -5.300814246746624),
                                    ("this <day-of-week>evening|night", -5.300814246746624),
                                    ("this <time>afternoon", -5.300814246746624),
                                    ("intersectnoon", -4.895349138638459),
                                    ("this <day-of-week>early morning", -5.300814246746624),
                                    ("intersectearly morning", -4.6076670661866785),
                                    ("intersectmorning", -2.497453865840089),
                                    ("<day-of-month>afternoon", -4.048051278251256),
                                    ("Mondaymorning", -3.7967368499703498),
                                    ("<named-month> <day-of-month>early morning",
                                     -4.6076670661866785),
                                    ("this <cycle>early morning", -5.300814246746624),
                                    ("todaymorning", -3.914519885626733),
                                    ("Fridaynoon", -4.895349138638459),
                                    ("Fridayevening|night", -4.895349138638459)],
                               n = 178},
                   koData =
                     ClassData{prior = -2.4397862145075306, unseen = -4.382026634673881,
                               likelihoods =
                                 HashMap.fromList
                                   [("the day after tomorrowafternoon", -3.676300671907076),
                                    ("dayhour", -1.8845412026790211),
                                    ("<integer> (latent time-of-day)afternoon", -3.270835563798912),
                                    ("<day-of-month>evening|night", -3.676300671907076),
                                    ("<day-of-month>early morning", -3.676300671907076),
                                    ("hourhour", -2.423537703411708),
                                    ("<integer> (latent time-of-day)early morning",
                                     -3.270835563798912),
                                    ("the day after tomorrowmorning", -3.270835563798912),
                                    ("<day-of-month>morning", -2.5776883832389665),
                                    ("<integer> (latent time-of-day)morning", -3.270835563798912),
                                    ("<day-of-month>afternoon", -3.676300671907076)],
                               n = 17}}),
       ("<part-of-day> <dim time>",
        Classifier{okData =
                     ClassData{prior = -0.4930867994286091,
                               unseen = -5.3230099791384085,
                               likelihoods =
                                 HashMap.fromList
                                   [("tonight<integer> (latent time-of-day)", -3.708682081410116),
                                    ("morning<time-of-day> o'clock", -2.920224721045846),
                                    ("evening|night<time-of-day> o'clock", -3.120895416507997),
                                    ("morning<integer> (latent time-of-day)", -2.920224721045846),
                                    ("morningrelative minutes to|till|before <integer> (hour-of-day)",
                                     -4.624972813284271),
                                    ("hourhour", -1.1749852674526837),
                                    ("morningrelative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -3.9318256327243257),
                                    ("morninghalf after|past <integer> (hour-of-day)",
                                     -4.219507705176107),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -2.920224721045846),
                                    ("evening|night<integer> (latent time-of-day)",
                                     -3.120895416507997),
                                    ("afternoon<time-of-day> o'clock", -3.2386784521643803),
                                    ("hourminute", -1.916922612182061),
                                    ("morningquarter after|past <integer> (hour-of-day)",
                                     -4.219507705176107),
                                    ("afternoon<integer> (latent time-of-day)",
                                     -3.2386784521643803),
                                    ("early morning<time-of-day> o'clock", -4.624972813284271),
                                    ("afternoonhh:mm (time-of-day)", -4.624972813284271),
                                    ("morningthree quarter after|past <integer> (hour-of-day)",
                                     -4.219507705176107),
                                    ("noon<time-of-day> o'clock", -4.624972813284271),
                                    ("tonight<time-of-day> o'clock", -3.708682081410116),
                                    ("noon<integer> (latent time-of-day)", -4.624972813284271),
                                    ("early morning<integer> (latent time-of-day)",
                                     -4.624972813284271),
                                    ("morningrelative minutes after|past <integer> (hour-of-day)",
                                     -3.120895416507997)],
                               n = 91},
                   koData =
                     ClassData{prior = -0.9435032953990399,
                               unseen = -4.9344739331306915,
                               likelihoods =
                                 HashMap.fromList
                                   [("morning<time-of-day> o'clock", -2.2192034840549946),
                                    ("morning<integer> (latent time-of-day)", -2.2192034840549946),
                                    ("hourhour", -1.2383742310432684),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -2.5293584123588344),
                                    ("afternoon<time-of-day> o'clock", -3.1354942159291497),
                                    ("hourminute", -1.9315214116032136),
                                    ("afternoon<integer> (latent time-of-day)", -2.981343536101891),
                                    ("morningrelative minutes after|past <integer> (hour-of-day)",
                                     -2.624668592163159)],
                               n = 58}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -6.385194398997726,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.164630810015805),
                                    ("integer (0..10)month (grain)", -2.4516810021596798),
                                    ("integer (0..10)hour (grain)", -3.5502932908277893),
                                    ("<number>\20010/\20491week (grain)", -3.9856113620856353),
                                    ("integer (numeric)day (grain)", -3.5502932908277893),
                                    ("compose by multiplicationminute (grain)", -5.69035945432406),
                                    ("second", -3.744449305268747),
                                    ("integer (0..10)day (grain)", -3.29246418152569),
                                    ("number suffix: \21313month (grain)", -4.774068722449905),
                                    ("integer (0..10)year (grain)", -4.08092154188996),
                                    ("<number>\20010/\20491month (grain)", -3.6109179126442243),
                                    ("number suffix: \21313minute (grain)", -5.69035945432406),
                                    ("integer (numeric)year (grain)", -3.4390676557175652),
                                    ("integer (0..10)second (grain)", -3.744449305268747),
                                    ("day", -2.491686336773379),
                                    ("integer with consecutive unit modifiersday (grain)",
                                     -3.898599985096005),
                                    ("year", -3.0513021247088017),
                                    ("integer (0..10)minute (grain)", -3.29246418152569),
                                    ("hour", -3.338984197160583),
                                    ("integer (0..10)week (grain)", -3.6754564337817954),
                                    ("month", -1.6473081864895103),
                                    ("integer (numeric)minute (grain)", -4.591747165655951),
                                    ("<number>\20010/\20491hour (grain)", -4.774068722449905),
                                    ("integer (numeric)month (grain)", -2.576844145113686),
                                    ("integer with consecutive unit modifiersminute (grain)",
                                     -3.9856113620856353),
                                    ("minute", -2.719944988754359)],
                               n = 283}}),
       ("last last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> am|pm",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mm (time-of-day)", -1.252762968495368),
                                    ("<integer> (latent time-of-day)", -1.540445040947149),
                                    ("hour", -1.540445040947149), ("minute", -1.252762968495368)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 3}}),
       ("<day-of-month>",
        Classifier{okData =
                     ClassData{prior = -0.25642952894767645, unseen = -4.90527477843843,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.7869659357776002),
                                    ("number suffix: \21313", -2.8183982582710754),
                                    ("integer with consecutive unit modifiers", -1.11365016603265),
                                    ("integer (0..10)", -1.8533173622274883)],
                               n = 130},
                   koData =
                     ClassData{prior = -1.486377819676873, unseen = -3.7612001156935624,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer with consecutive unit modifiers",
                                     -1.3397743454849977),
                                    ("integer (0..10)", -0.37037378829689427)],
                               n = 38}}),
       ("number suffix: \19975",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("relative minutes after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.640037355245997, unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -3.0602707946915624),
                                    ("<integer> (latent time-of-day)integer with consecutive unit modifiers",
                                     -1.3256697393034558),
                                    ("<integer> (latent time-of-day)integer (numeric)",
                                     -1.6739764335716716),
                                    ("hour", -0.7576857016975165)],
                               n = 29},
                   koData =
                     ClassData{prior = -0.7492366472109889, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -2.9618307218783095),
                                    ("<integer> (latent time-of-day)number suffix: \21313",
                                     -1.9810014688665833),
                                    ("<integer> (latent time-of-day)integer (0..10)",
                                     -1.1700712526502546),
                                    ("hour", -0.7646061445420903)],
                               n = 26}}),
       ("intersect by \",\"",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.330733340286331,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -2.2380465718564744),
                                    ("Sunday<named-month> <day-of-month>", -1.6094379124341003),
                                    ("Sundaymonth (numeric with month symbol)",
                                     -2.2380465718564744),
                                    ("dayday", -0.9501922835498364),
                                    ("Sundayintersect", -1.6094379124341003)],
                               n = 35},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer with consecutive unit modifiers",
        Classifier{okData =
                     ClassData{prior = -0.20661424936299916,
                               unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("number suffix: \21313integer (0..10)", -0.8266785731844679),
                                    ("compose by multiplicationinteger (0..10)",
                                     -2.0794415416798357),
                                    ("integer (0..10)integer (0..10)", -0.8266785731844679)],
                               n = 61},
                   koData =
                     ClassData{prior = -1.6784307839210517, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("number suffix: \21313integer (0..10)", -0.7537718023763802),
                                    ("integer (0..10)integer (0..10)", -0.7537718023763802)],
                               n = 14}}),
       ("second (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("\22307\35806\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -1.3217558399823195,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.9007865453381898), ("Sunday", -1.3862943611198906),
                                    ("Tuesday", -1.6739764335716716)],
                               n = 12},
                   koData =
                     ClassData{prior = -0.3101549283038396, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> o'clock", -3.20545280453606),
                                    ("<integer> (latent time-of-day)", -0.9718605830289657),
                                    ("month (numeric with month symbol)", -2.6946271807700692),
                                    ("hour", -0.9028677115420143), ("month", -2.6946271807700692)],
                               n = 33}}),
       ("the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = -1.2039728043259361,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("\22919\22899\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("noon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -0.9555114450274363, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.5040773967762742),
                                    ("day", -0.8979415932059586), ("Tuesday", -1.5040773967762742)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.48550781578170077,
                               unseen = -3.6888794541139363,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.8909729238898653),
                                    ("month (numeric with month symbol)", -2.9704144655697013),
                                    ("hour", -0.8909729238898653), ("month", -2.9704144655697013)],
                               n = 16}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.7375989431307791, unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.540445040947149),
                                    ("month (grain)", -1.540445040947149),
                                    ("year (grain)", -2.639057329615259),
                                    ("week (grain)", -1.540445040947149),
                                    ("year", -2.639057329615259), ("month", -1.540445040947149)],
                               n = 11},
                   koData =
                     ClassData{prior = -0.6505875661411494,
                               unseen = -3.4339872044851463,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.8362480242006186),
                                    ("week (grain)", -0.8362480242006186)],
                               n = 12}}),
       ("next n <cycle>",
        Classifier{okData =
                     ClassData{prior = -2.353049741019416e-2,
                               unseen = -4.624972813284271,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.41789593950504),
                                    ("integer (0..10)hour (grain)", -2.6692103677859462),
                                    ("<number>\20010/\20491week (grain)", -3.005682604407159),
                                    ("second", -2.8233610476132043),
                                    ("integer (0..10)day (grain)", -2.5356789751614235),
                                    ("integer (0..10)year (grain)", -3.228826155721369),
                                    ("<number>\20010/\20491month (grain)", -2.8233610476132043),
                                    ("integer (0..10)second (grain)", -2.8233610476132043),
                                    ("day", -2.5356789751614235), ("year", -3.228826155721369),
                                    ("integer (0..10)minute (grain)", -2.6692103677859462),
                                    ("hour", -2.41789593950504),
                                    ("integer (0..10)week (grain)", -3.005682604407159),
                                    ("month", -2.8233610476132043),
                                    ("<number>\20010/\20491hour (grain)", -3.5165082281731497),
                                    ("minute", -2.6692103677859462)],
                               n = 42},
                   koData =
                     ClassData{prior = -3.7612001156935624, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)day (grain)", -2.2512917986064953),
                                    ("day", -2.2512917986064953)],
                               n = 1}}),
       ("\19975\22307\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20799\31461\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Tuesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-month> <day-of-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -5.429345628954441,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (numeric with month symbol)integer with consecutive unit modifiers",
                                     -1.6407603835631415),
                                    ("month (numeric with month symbol)integer (numeric)",
                                     -1.6637499017878403),
                                    ("month (numeric with month symbol)number suffix: \21313",
                                     -3.3455084758015667),
                                    ("month", -0.7064511461863081),
                                    ("month (numeric with month symbol)integer (0..10)",
                                     -2.4292177439274116)],
                               n = 111},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\21171\21160\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (0..10)",
        Classifier{okData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -5.641907070938114,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 280},
                   koData =
                     ClassData{prior = -1.2039728043259361, unseen = -4.804021044733257,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 120}}),
       ("last n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.605170185988091,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.9856819377004897),
                                    ("integer (0..10)month (grain)", -3.4965075614664802),
                                    ("integer (0..10)hour (grain)", -2.3978952727983707),
                                    ("second", -2.649209701079277),
                                    ("integer (0..10)day (grain)", -2.9856819377004897),
                                    ("integer (0..10)year (grain)", -3.4965075614664802),
                                    ("<number>\20010/\20491month (grain)", -2.3978952727983707),
                                    ("integer (0..10)second (grain)", -2.649209701079277),
                                    ("day", -2.9856819377004897), ("year", -3.4965075614664802),
                                    ("integer (0..10)minute (grain)", -2.3978952727983707),
                                    ("hour", -2.3978952727983707),
                                    ("integer (0..10)week (grain)", -2.9856819377004897),
                                    ("month", -2.1972245773362196),
                                    ("minute", -2.3978952727983707)],
                               n = 42},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("<number>\20010/\20491", -0.1823215567939546)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)", -0.1823215567939546)],
                               n = 4}}),
       ("n <cycle> last",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.04305126783455,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.4159137783010487),
                                    ("integer (0..10)hour (grain)", -2.9267394020670396),
                                    ("<number>\20010/\20491week (grain)", -2.9267394020670396),
                                    ("second", -2.9267394020670396),
                                    ("integer (0..10)day (grain)", -2.4159137783010487),
                                    ("integer (0..10)year (grain)", -2.9267394020670396),
                                    ("<number>\20010/\20491month (grain)", -2.9267394020670396),
                                    ("integer (0..10)second (grain)", -2.9267394020670396),
                                    ("day", -2.4159137783010487), ("year", -2.9267394020670396),
                                    ("integer (0..10)minute (grain)", -2.9267394020670396),
                                    ("hour", -2.4159137783010487),
                                    ("integer (0..10)week (grain)", -2.9267394020670396),
                                    ("month", -2.9267394020670396),
                                    ("<number>\20010/\20491hour (grain)", -2.9267394020670396),
                                    ("minute", -2.9267394020670396)],
                               n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.871201010907891,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 46},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (numeric)",
                                     -0.8472978603872037),
                                    ("hour", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (0..10)",
                                     -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 1}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -3.5553480614894135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 33},
                   koData =
                     ClassData{prior = -0.916290731874155, unseen = -3.1780538303479458,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 22}}),
       ("<number>\20010/\20491",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4339872044851463,
                               likelihoods = HashMap.fromList [("integer (0..10)", 0.0)], n = 29},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("compose by multiplication",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)number suffix: \21313", 0.0)],
                               n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24773\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("nth <time> of <time> 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -0.6931471805599453),
                                    ("month (numeric with month symbol)ordinal (digits)Monday",
                                     -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.634728988229636,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.5455312716044354),
                                    ("evening|night", -3.0155349008501706),
                                    ("Monday", -2.5455312716044354),
                                    ("Friday", -3.0155349008501706), ("day", -1.2576769832977972),
                                    ("<dim time> <part-of-day>", -3.0155349008501706),
                                    ("<part-of-day> <dim time>", -2.4277482359480516),
                                    ("hour", -1.6805338341178306), ("Tuesday", -2.2270775404859005),
                                    ("week-end", -3.5263605246161616)],
                               n = 46},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [], n = 0}})]