-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.ZH_MO (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("relative minutes to|till|before <integer> (hour-of-day) with minute unit",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (numeric)",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> timezone",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> am|pm", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Thursday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.17958557697507987,
                               unseen = -5.220355825078324,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 183},
                   koData =
                     ClassData{prior = -1.8055527913603908,
                               unseen = -3.6375861597263857,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 36}}),
       ("the day before yesterday",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\22269\38469\28040\36153\32773\26435\30410\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24314\20891\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next next year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453), ("Sunday", -0.6931471805599453)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tonight",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = -1.4469189829363254,
                               unseen = -3.4011973816621555,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 28},
                   koData =
                     ClassData{prior = -0.2682639865946794, unseen = -4.532599493153256,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 91}}),
       ("<time-of-day> o'clock",
        Classifier{okData =
                     ClassData{prior = -0.5714502455824255, unseen = -4.59511985013459,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 48},
                   koData =
                     ClassData{prior = -0.831733343846092, unseen = -4.343805421853684,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 37}}),
       ("national day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("number suffix: \21313",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 47},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20803\26086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.1166249579357558,
                               unseen = -7.3901814282264295,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -5.780126041243535),
                                    ("dayhour", -2.236272359179856),
                                    ("last last year<named-month> <day-of-month>",
                                     -6.69641677311769),
                                    ("daymonth", -5.310122411997799),
                                    ("<named-month> <day-of-month><part-of-day> <dim time>",
                                     -4.170688128809434),
                                    ("monthday", -2.4059573319692986),
                                    ("this yearmonth (numeric with month symbol)",
                                     -6.003269592557745),
                                    ("yearhour", -3.4192720401255134),
                                    ("this <cycle><named-month> <day-of-month>",
                                     -6.003269592557745),
                                    ("<day-of-month>noon", -6.69641677311769),
                                    ("last <cycle><day-of-month>", -6.290951665009525),
                                    ("<dim time> <part-of-day>half after|past <integer> (hour-of-day)",
                                     -6.290951665009525),
                                    ("this <cycle>month (numeric with month symbol)",
                                     -6.003269592557745),
                                    ("todayrelative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -5.780126041243535),
                                    ("last last yearintersect", -4.824614596216098),
                                    ("intersect by \",\"<day-of-month>", -4.681513752575425),
                                    ("next yearintersect", -4.824614596216098),
                                    ("<dim time> <part-of-day>quarter after|past <integer> (hour-of-day)",
                                     -6.290951665009525),
                                    ("<day-of-month><time-of-day> o'clock", -4.345041515954212),
                                    ("year (numeric with year symbol)<named-month> <day-of-month>",
                                     -4.345041515954212),
                                    ("<dim time> <part-of-day><time-of-day> o'clock",
                                     -3.3822307684451642),
                                    ("<day-of-month><part-of-day> <dim time>", -4.022268123691161),
                                    ("monthhour", -2.735603603520112),
                                    ("last last year<dim time> <part-of-day>", -6.290951665009525),
                                    ("year (numeric with year symbol)month (numeric with month symbol)",
                                     -4.445124974511194),
                                    ("dayday", -3.346512685843085),
                                    ("todayrelative minutes after|past <integer> (hour-of-day)",
                                     -5.443653804622322),
                                    ("hourhour", -2.878704447160785),
                                    ("this <cycle><day-of-month>", -6.003269592557745),
                                    ("this <cycle><part-of-day> <dim time>", -5.192339376341415),
                                    ("<named-month> <day-of-month>noon", -6.69641677311769),
                                    ("last yearmonth (numeric with month symbol)",
                                     -6.69641677311769),
                                    ("this <time><time-of-day> o'clock", -5.780126041243535),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day)",
                                     -5.443653804622322),
                                    ("<dim time> <part-of-day>three quarter after|past <integer> (hour-of-day)",
                                     -6.290951665009525),
                                    ("this <cycle><time-of-day> o'clock", -6.290951665009525),
                                    ("last year<named-month> <day-of-month>", -6.69641677311769),
                                    ("the day after the day after tomorrow<part-of-day> <dim time>",
                                     -5.780126041243535),
                                    ("hourminute", -4.556350609621419),
                                    ("next yearmonth (numeric with month symbol)",
                                     -6.69641677311769),
                                    ("absorption of , after named daymonth (numeric with month symbol)",
                                     -5.310122411997799),
                                    ("next next yearmonth (numeric with month symbol)",
                                     -6.69641677311769),
                                    ("month (numeric with month symbol)<day-of-month>",
                                     -2.680033752365301),
                                    ("<named-month> <day-of-month><time-of-day> o'clock",
                                     -4.445124974511194),
                                    ("<dim time> <part-of-day>relative minutes to|till|before <integer> (hour-of-day)",
                                     -6.290951665009525),
                                    ("month (numeric with month symbol)<dim time> <part-of-day>",
                                     -3.863203429061474),
                                    ("next next year<named-month> <day-of-month>",
                                     -6.69641677311769),
                                    ("absorption of , after named day<named-month> <day-of-month>",
                                     -4.681513752575425),
                                    ("this yearintersect", -6.003269592557745),
                                    ("next year<dim time> <part-of-day>", -6.290951665009525),
                                    ("intersect<time-of-day> o'clock", -3.5394163519675765),
                                    ("yearmonth", -4.022268123691161),
                                    ("intersect<dim time> <part-of-day>", -5.780126041243535),
                                    ("this year<named-month> <day-of-month>", -6.003269592557745),
                                    ("next next yearintersect", -4.824614596216098),
                                    ("intersect<day-of-month>", -3.5829014639073153),
                                    ("dayminute", -3.7260023075479887),
                                    ("intersect<part-of-day> <dim time>", -3.4977436555670085),
                                    ("last year<dim time> <part-of-day>", -6.290951665009525),
                                    ("todayhalf after|past <integer> (hour-of-day)",
                                     -6.69641677311769),
                                    ("absorption of , after named dayintersect",
                                     -4.681513752575425),
                                    ("today<time-of-day> o'clock", -6.290951665009525),
                                    ("intersectnoon", -6.69641677311769),
                                    ("tonight<time-of-day> o'clock", -5.780126041243535),
                                    ("last yearintersect", -4.824614596216098),
                                    ("next next year<dim time> <part-of-day>", -6.290951665009525),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -5.192339376341415),
                                    ("intersectintersect", -4.824614596216098),
                                    ("today<part-of-day> <dim time>", -5.192339376341415),
                                    ("the day after the day after tomorrow<time-of-day> o'clock",
                                     -6.69641677311769),
                                    ("year (numeric with year symbol)intersect",
                                     -4.345041515954212),
                                    ("yearday", -3.2786900895043236),
                                    ("next year<named-month> <day-of-month>", -6.69641677311769),
                                    ("month (numeric with month symbol)intersect",
                                     -3.3642122629424858),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -5.780126041243535),
                                    ("this <cycle>half after|past <integer> (hour-of-day)",
                                     -6.69641677311769),
                                    ("this <cycle>intersect", -6.003269592557745),
                                    ("last last yearmonth (numeric with month symbol)",
                                     -6.69641677311769)],
                               n = 768},
                   koData =
                     ClassData{prior = -2.206537799482887, unseen = -5.6131281063880705,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -3.41224721784874),
                                    ("dayhour", -1.677646162460634),
                                    ("monthday", -4.916324614625014),
                                    ("the day after tomorrow<part-of-day> <dim time>",
                                     -4.000033882750859),
                                    ("month (numeric with month symbol)next n <cycle>",
                                     -4.916324614625014),
                                    ("<day-of-month><time-of-day> o'clock", -3.817712325956905),
                                    ("<dim time> <part-of-day><time-of-day> o'clock",
                                     -2.7762584511287436),
                                    ("todayrelative minutes after|past <integer> (hour-of-day)",
                                     -3.817712325956905),
                                    ("hourhour", -2.7762584511287436),
                                    ("this <cycle><part-of-day> <dim time>", -2.9014215940827497),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day)",
                                     -3.817712325956905),
                                    ("this <cycle><dim time> <part-of-day>", -4.51085950651685),
                                    ("this <cycle><time-of-day> o'clock", -3.6635616461296463),
                                    ("hourminute", -3.41224721784874),
                                    ("weekhour", -4.51085950651685),
                                    ("dayminute", -2.665032816018519),
                                    ("the day after tomorrow<time-of-day> o'clock",
                                     -4.916324614625014),
                                    ("today<time-of-day> o'clock", -3.6635616461296463),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -3.41224721784874),
                                    ("today<part-of-day> <dim time>", -2.9014215940827497)],
                               n = 95}}),
       ("half after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("early morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.7884573603642702, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -0.6061358035703156, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18}}),
       ("Saturday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.7472144018302211,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("month (grain)", -1.791759469228055),
                                    ("year (grain)", -2.4849066497880004),
                                    ("week (grain)", -1.3862943611198906),
                                    ("year", -2.4849066497880004), ("month", -1.791759469228055)],
                               n = 9},
                   koData =
                     ClassData{prior = -0.6418538861723948, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.8602012652231115),
                                    ("week (grain)", -0.8602012652231115)],
                               n = 10}}),
       ("last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.0943445622221,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.9980959022258835),
                                    ("Monday", -1.9980959022258835), ("Friday", -2.691243082785829),
                                    ("day", -0.7453329337305155), ("Tuesday", -1.6796421711073488)],
                               n = 27},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes after|past <integer> (hour-of-day) with minute unit",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -2.4849066497880004),
                                    ("<integer> (latent time-of-day)integer with consecutive unit modifiers",
                                     -1.2321436812926323),
                                    ("<integer> (latent time-of-day)integer (numeric)",
                                     -1.791759469228055),
                                    ("hour", -0.7801585575495751)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd/yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening|night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.258096538021482,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 24},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day before the day before yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes to|till|before <integer> (hour-of-day) with minute unit reversed",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)<integer> (latent time-of-day)",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm (time-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> (latent time-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.4656336295746172, unseen = -4.51085950651685,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.5679840376059393),
                                    ("integer with consecutive unit modifiers",
                                     -3.4011973816621555),
                                    ("integer (0..10)", -0.9444616088408514)],
                               n = 86},
                   koData =
                     ClassData{prior = -0.9881552931037991, unseen = -4.02535169073515,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -2.3978952727983707),
                                    ("integer (0..10)", -0.29376111852816306),
                                    ("<number>\20010/\20491", -1.927891643552635)],
                               n = 51}}),
       ("nth <time> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -0.6931471805599453),
                                    ("month (numeric with month symbol)ordinal (digits)Monday",
                                     -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (numeric with month symbol)",
        Classifier{okData =
                     ClassData{prior = -0.16462197969455372,
                               unseen = -4.605170185988091,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8109302162163288),
                                    ("number suffix: \21313", -2.9856819377004897),
                                    ("integer (0..10)", -0.7032995520239633)],
                               n = 95},
                   koData =
                     ClassData{prior = -1.8852855272388784,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (0..10)", -1.9459101490553135),
                                    ("<number>\20010/\20491", -0.2719337154836418)],
                               n = 17}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = -0.9108706644048158,
                               unseen = -3.6635616461296463,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 37},
                   koData =
                     ClassData{prior = -0.5144553918165694, unseen = -4.04305126783455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 55}}),
       ("year (numeric with year symbol)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24858\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day after the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, negative or minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 4}}),
       ("Friday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("three quarter after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\28595\38376\22238\24402\32426\24565\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("fractional number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8}}),
       ("Sunday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("afternoon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> from now",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.5671064596645803, unseen = -4.442651256490317,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.9459101490553135),
                                    ("month (grain)", -3.044522437723423),
                                    ("year (grain)", -2.4849066497880004),
                                    ("week (grain)", -1.9459101490553135),
                                    ("day", -1.486377819676873), ("year", -2.4849066497880004),
                                    ("month", -3.044522437723423),
                                    ("day (grain)", -1.486377819676873)],
                               n = 38},
                   koData =
                     ClassData{prior = -0.8373967894044921, unseen = -4.204692619390966,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.7884573603642702),
                                    ("week (grain)", -0.7884573603642702)],
                               n = 29}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -0.48550781578170077,
                               unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16},
                   koData =
                     ClassData{prior = -0.9555114450274363,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10}}),
       ("<dim time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -9.694194519223047e-2,
                               unseen = -5.924255797414532,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.7976144402405566),
                                    ("this <time>early morning", -5.2284312390838705),
                                    ("<day-of-month>evening|night", -3.61899332664977),
                                    ("national dayevening|night", -4.822966130975706),
                                    ("<day-of-month>early morning", -4.1298189504157605),
                                    ("the day after the day after tomorrowafternoon",
                                     -5.2284312390838705),
                                    ("<named-month> <day-of-month>morning", -2.8770559819203925),
                                    ("Fridayafternoon", -4.822966130975706),
                                    ("<named-month> <day-of-month>evening|night",
                                     -3.9756682705885025),
                                    ("intersectafternoon", -4.312140507209715),
                                    ("this <time>evening|night", -5.2284312390838705),
                                    ("\24773\20154\33410evening|night", -4.822966130975706),
                                    ("<day-of-month>morning", -2.786084203714666),
                                    ("this <day-of-week>afternoon", -5.2284312390838705),
                                    ("Fridayearly morning", -4.822966130975706),
                                    ("Fridaymorning", -4.822966130975706),
                                    ("the day after the day after tomorrowmorning",
                                     -4.822966130975706),
                                    ("\20799\31461\33410afternoon", -4.822966130975706),
                                    ("<named-month> <day-of-month>afternoon", -4.312140507209715),
                                    ("this <cycle>morning", -3.8421368779639797),
                                    ("todayearly morning", -5.2284312390838705),
                                    ("intersectevening|night", -3.9756682705885025),
                                    ("this <day-of-week>evening|night", -5.2284312390838705),
                                    ("this <time>afternoon", -5.2284312390838705),
                                    ("this <day-of-week>early morning", -5.2284312390838705),
                                    ("intersectearly morning", -4.535284058523925),
                                    ("intersectmorning", -2.4250708581773353),
                                    ("<day-of-month>afternoon", -3.9756682705885025),
                                    ("Mondaymorning", -3.7243538423075964),
                                    ("<named-month> <day-of-month>early morning",
                                     -4.535284058523925),
                                    ("this <cycle>early morning", -5.2284312390838705),
                                    ("todaymorning", -3.8421368779639797),
                                    ("Fridayevening|night", -4.822966130975706)],
                               n = 167},
                   koData =
                     ClassData{prior = -2.3817224135527697, unseen = -4.304065093204169,
                               likelihoods =
                                 HashMap.fromList
                                   [("the day after tomorrowafternoon", -3.597312260588446),
                                    ("dayhour", -1.8055527913603908),
                                    ("<integer> (latent time-of-day)afternoon",
                                     -3.1918471524802814),
                                    ("<day-of-month>evening|night", -3.597312260588446),
                                    ("<day-of-month>early morning", -3.597312260588446),
                                    ("hourhour", -2.344549292093078),
                                    ("<integer> (latent time-of-day)early morning",
                                     -3.1918471524802814),
                                    ("the day after tomorrowmorning", -3.1918471524802814),
                                    ("<day-of-month>morning", -2.498699971920336),
                                    ("<integer> (latent time-of-day)morning", -3.1918471524802814),
                                    ("<day-of-month>afternoon", -3.597312260588446)],
                               n = 17}}),
       ("<part-of-day> <dim time>",
        Classifier{okData =
                     ClassData{prior = -0.5017962170465965, unseen = -5.293304824724492,
                               likelihoods =
                                 HashMap.fromList
                                   [("tonight<integer> (latent time-of-day)", -3.6788291182604347),
                                    ("morning<time-of-day> o'clock", -2.890371757896165),
                                    ("evening|night<time-of-day> o'clock", -3.0910424533583156),
                                    ("morning<integer> (latent time-of-day)", -2.890371757896165),
                                    ("morningrelative minutes to|till|before <integer> (hour-of-day)",
                                     -4.59511985013459),
                                    ("hourhour", -1.177393166521224),
                                    ("morningrelative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -3.9019726695746444),
                                    ("morninghalf after|past <integer> (hour-of-day)",
                                     -4.189654742026425),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -2.890371757896165),
                                    ("evening|night<integer> (latent time-of-day)",
                                     -3.0910424533583156),
                                    ("afternoon<time-of-day> o'clock", -3.2088254890146994),
                                    ("hourminute", -1.8870696490323797),
                                    ("morningquarter after|past <integer> (hour-of-day)",
                                     -4.189654742026425),
                                    ("afternoon<integer> (latent time-of-day)",
                                     -3.2088254890146994),
                                    ("early morning<time-of-day> o'clock", -4.59511985013459),
                                    ("afternoonhh:mm (time-of-day)", -4.59511985013459),
                                    ("morningthree quarter after|past <integer> (hour-of-day)",
                                     -4.189654742026425),
                                    ("tonight<time-of-day> o'clock", -3.6788291182604347),
                                    ("early morning<integer> (latent time-of-day)",
                                     -4.59511985013459),
                                    ("morningrelative minutes after|past <integer> (hour-of-day)",
                                     -3.0910424533583156)],
                               n = 89},
                   koData =
                     ClassData{prior = -0.9299895762323169, unseen = -4.919980925828125,
                               likelihoods =
                                 HashMap.fromList
                                   [("morning<time-of-day> o'clock", -2.204604684633842),
                                    ("morning<integer> (latent time-of-day)", -2.204604684633842),
                                    ("hourhour", -1.2237754316221157),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -2.5147596129376812),
                                    ("afternoon<time-of-day> o'clock", -3.120895416507997),
                                    ("hourminute", -1.916922612182061),
                                    ("afternoon<integer> (latent time-of-day)", -2.966744736680739),
                                    ("morningrelative minutes after|past <integer> (hour-of-day)",
                                     -2.6100697927420065)],
                               n = 58}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -6.3818160174060985,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.1612467120315646),
                                    ("integer (0..10)month (grain)", -2.4482969041754394),
                                    ("integer (0..10)hour (grain)", -3.546909192843549),
                                    ("<number>\20010/\20491week (grain)", -3.9822272641013945),
                                    ("integer (numeric)day (grain)", -3.546909192843549),
                                    ("compose by multiplicationminute (grain)", -5.68697535633982),
                                    ("second", -3.7410652072845063),
                                    ("integer (0..10)day (grain)", -3.289080083541449),
                                    ("number suffix: \21313month (grain)", -4.770684624465665),
                                    ("integer (0..10)year (grain)", -4.07753744390572),
                                    ("<number>\20010/\20491month (grain)", -3.607533814659984),
                                    ("number suffix: \21313minute (grain)", -5.68697535633982),
                                    ("integer (numeric)year (grain)", -3.435683557733325),
                                    ("integer (0..10)second (grain)", -3.7410652072845063),
                                    ("day", -2.4883022387891387),
                                    ("integer with consecutive unit modifiersday (grain)",
                                     -3.895215887111765),
                                    ("year", -3.0479180267245614),
                                    ("integer (0..10)minute (grain)", -3.289080083541449),
                                    ("hour", -3.335600099176342),
                                    ("integer (0..10)week (grain)", -3.672072335797555),
                                    ("month", -1.6527347181874246),
                                    ("integer (numeric)minute (grain)", -4.58836306767171),
                                    ("<number>\20010/\20491hour (grain)", -4.770684624465665),
                                    ("integer (numeric)month (grain)", -2.5959329029815037),
                                    ("integer with consecutive unit modifiersminute (grain)",
                                     -3.9822272641013945),
                                    ("minute", -2.716560890770119)],
                               n = 282}}),
       ("last last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> am|pm",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mm (time-of-day)", -1.252762968495368),
                                    ("<integer> (latent time-of-day)", -1.540445040947149),
                                    ("hour", -1.540445040947149), ("minute", -1.252762968495368)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 3}}),
       ("<day-of-month>",
        Classifier{okData =
                     ClassData{prior = -0.259957524436926, unseen = -4.890349128221754,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8052644786806514),
                                    ("number suffix: \21313", -2.803360380906535),
                                    ("integer with consecutive unit modifiers",
                                     -1.0986122886681098),
                                    ("integer (0..10)", -1.8382794848629478)],
                               n = 128},
                   koData =
                     ClassData{prior = -1.4744016286301576,
                               unseen = -3.7612001156935624,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer with consecutive unit modifiers",
                                     -1.3397743454849977),
                                    ("integer (0..10)", -0.37037378829689427)],
                               n = 38}}),
       ("number suffix: \19975",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("relative minutes after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.640037355245997, unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -3.0602707946915624),
                                    ("<integer> (latent time-of-day)integer with consecutive unit modifiers",
                                     -1.3256697393034558),
                                    ("<integer> (latent time-of-day)integer (numeric)",
                                     -1.6739764335716716),
                                    ("hour", -0.7576857016975165)],
                               n = 29},
                   koData =
                     ClassData{prior = -0.7492366472109889, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -2.9618307218783095),
                                    ("<integer> (latent time-of-day)number suffix: \21313",
                                     -1.9810014688665833),
                                    ("<integer> (latent time-of-day)integer (0..10)",
                                     -1.1700712526502546),
                                    ("hour", -0.7646061445420903)],
                               n = 26}}),
       ("intersect by \",\"",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.330733340286331,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -2.2380465718564744),
                                    ("Sunday<named-month> <day-of-month>", -1.6094379124341003),
                                    ("Sundaymonth (numeric with month symbol)",
                                     -2.2380465718564744),
                                    ("dayday", -0.9501922835498364),
                                    ("Sundayintersect", -1.6094379124341003)],
                               n = 35},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer with consecutive unit modifiers",
        Classifier{okData =
                     ClassData{prior = -0.20661424936299916,
                               unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("number suffix: \21313integer (0..10)", -0.8266785731844679),
                                    ("compose by multiplicationinteger (0..10)",
                                     -2.0794415416798357),
                                    ("integer (0..10)integer (0..10)", -0.8266785731844679)],
                               n = 61},
                   koData =
                     ClassData{prior = -1.6784307839210517, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("number suffix: \21313integer (0..10)", -0.7537718023763802),
                                    ("integer (0..10)integer (0..10)", -0.7537718023763802)],
                               n = 14}}),
       ("second (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("\22307\35806\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -1.3217558399823195,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.9007865453381898), ("Sunday", -1.3862943611198906),
                                    ("Tuesday", -1.6739764335716716)],
                               n = 12},
                   koData =
                     ClassData{prior = -0.3101549283038396, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> o'clock", -3.20545280453606),
                                    ("<integer> (latent time-of-day)", -0.9718605830289657),
                                    ("month (numeric with month symbol)", -2.6946271807700692),
                                    ("hour", -0.9028677115420143), ("month", -2.6946271807700692)],
                               n = 33}}),
       ("the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = -1.2039728043259361,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("\22919\22899\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("noon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -0.9555114450274363, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.5040773967762742),
                                    ("day", -0.8979415932059586), ("Tuesday", -1.5040773967762742)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.48550781578170077,
                               unseen = -3.6888794541139363,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.8909729238898653),
                                    ("month (numeric with month symbol)", -2.9704144655697013),
                                    ("hour", -0.8909729238898653), ("month", -2.9704144655697013)],
                               n = 16}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.7375989431307791, unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.540445040947149),
                                    ("month (grain)", -1.540445040947149),
                                    ("year (grain)", -2.639057329615259),
                                    ("week (grain)", -1.540445040947149),
                                    ("year", -2.639057329615259), ("month", -1.540445040947149)],
                               n = 11},
                   koData =
                     ClassData{prior = -0.6505875661411494,
                               unseen = -3.4339872044851463,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.8362480242006186),
                                    ("week (grain)", -0.8362480242006186)],
                               n = 12}}),
       ("next n <cycle>",
        Classifier{okData =
                     ClassData{prior = -2.353049741019416e-2,
                               unseen = -4.624972813284271,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.41789593950504),
                                    ("integer (0..10)hour (grain)", -2.6692103677859462),
                                    ("<number>\20010/\20491week (grain)", -3.005682604407159),
                                    ("second", -2.8233610476132043),
                                    ("integer (0..10)day (grain)", -2.5356789751614235),
                                    ("integer (0..10)year (grain)", -3.228826155721369),
                                    ("<number>\20010/\20491month (grain)", -2.8233610476132043),
                                    ("integer (0..10)second (grain)", -2.8233610476132043),
                                    ("day", -2.5356789751614235), ("year", -3.228826155721369),
                                    ("integer (0..10)minute (grain)", -2.6692103677859462),
                                    ("hour", -2.41789593950504),
                                    ("integer (0..10)week (grain)", -3.005682604407159),
                                    ("month", -2.8233610476132043),
                                    ("<number>\20010/\20491hour (grain)", -3.5165082281731497),
                                    ("minute", -2.6692103677859462)],
                               n = 42},
                   koData =
                     ClassData{prior = -3.7612001156935624, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)day (grain)", -2.2512917986064953),
                                    ("day", -2.2512917986064953)],
                               n = 1}}),
       ("\19975\22307\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20799\31461\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Tuesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-month> <day-of-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -5.420534999272286,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (numeric with month symbol)integer with consecutive unit modifiers",
                                     -1.6319107682861589),
                                    ("month (numeric with month symbol)integer (numeric)",
                                     -1.6784307839210517),
                                    ("month (numeric with month symbol)number suffix: \21313",
                                     -3.3366588605245844),
                                    ("month", -0.706570200892086),
                                    ("month (numeric with month symbol)integer (0..10)",
                                     -2.4203681286504293)],
                               n = 110},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\21171\21160\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (0..10)",
        Classifier{okData =
                     ClassData{prior = -0.351662402115188, unseen = -5.641907070938114,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 280},
                   koData =
                     ClassData{prior = -1.215767380818773, unseen = -4.787491742782046,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 118}}),
       ("last n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.605170185988091,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.9856819377004897),
                                    ("integer (0..10)month (grain)", -3.4965075614664802),
                                    ("integer (0..10)hour (grain)", -2.3978952727983707),
                                    ("second", -2.649209701079277),
                                    ("integer (0..10)day (grain)", -2.9856819377004897),
                                    ("integer (0..10)year (grain)", -3.4965075614664802),
                                    ("<number>\20010/\20491month (grain)", -2.3978952727983707),
                                    ("integer (0..10)second (grain)", -2.649209701079277),
                                    ("day", -2.9856819377004897), ("year", -3.4965075614664802),
                                    ("integer (0..10)minute (grain)", -2.3978952727983707),
                                    ("hour", -2.3978952727983707),
                                    ("integer (0..10)week (grain)", -2.9856819377004897),
                                    ("month", -2.1972245773362196),
                                    ("minute", -2.3978952727983707)],
                               n = 42},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("<number>\20010/\20491", -0.1823215567939546)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)", -0.1823215567939546)],
                               n = 4}}),
       ("n <cycle> last",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.04305126783455,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.4159137783010487),
                                    ("integer (0..10)hour (grain)", -2.9267394020670396),
                                    ("<number>\20010/\20491week (grain)", -2.9267394020670396),
                                    ("second", -2.9267394020670396),
                                    ("integer (0..10)day (grain)", -2.4159137783010487),
                                    ("integer (0..10)year (grain)", -2.9267394020670396),
                                    ("<number>\20010/\20491month (grain)", -2.9267394020670396),
                                    ("integer (0..10)second (grain)", -2.9267394020670396),
                                    ("day", -2.4159137783010487), ("year", -2.9267394020670396),
                                    ("integer (0..10)minute (grain)", -2.9267394020670396),
                                    ("hour", -2.4159137783010487),
                                    ("integer (0..10)week (grain)", -2.9267394020670396),
                                    ("month", -2.9267394020670396),
                                    ("<number>\20010/\20491hour (grain)", -2.9267394020670396),
                                    ("minute", -2.9267394020670396)],
                               n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.871201010907891,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 46},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (numeric)",
                                     -0.8472978603872037),
                                    ("hour", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (0..10)",
                                     -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 1}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -3.5553480614894135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 33},
                   koData =
                     ClassData{prior = -0.916290731874155, unseen = -3.1780538303479458,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 22}}),
       ("<number>\20010/\20491",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4339872044851463,
                               likelihoods = HashMap.fromList [("integer (0..10)", 0.0)], n = 29},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("compose by multiplication",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)number suffix: \21313", 0.0)],
                               n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24773\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("nth <time> of <time> 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -0.6931471805599453),
                                    ("month (numeric with month symbol)ordinal (digits)Monday",
                                     -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.59511985013459,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.505525936990736),
                                    ("evening|night", -2.9755295662364714),
                                    ("Monday", -2.505525936990736), ("Friday", -3.1986731175506815),
                                    ("day", -1.252762968495368),
                                    ("<dim time> <part-of-day>", -3.1986731175506815),
                                    ("<part-of-day> <dim time>", -2.3877429013343523),
                                    ("hour", -1.6945957207744071), ("Tuesday", -2.187072205872201),
                                    ("week-end", -3.4863551900024623)],
                               n = 44},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [], n = 0}})]