-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.ZH_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("relative minutes to|till|before <integer> (hour-of-day) with minute unit",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (numeric)",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> timezone",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> am|pm", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Thursday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.16893998809812322, unseen = -5.10594547390058,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 163},
                   koData =
                     ClassData{prior = -1.8614928072427301,
                               unseen = -3.4657359027997265,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 30}}),
       ("the day before yesterday",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\22269\38469\28040\36153\32773\26435\30410\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24314\20891\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next next year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd",
        Classifier{okData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.2231435513142097, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453), ("Sunday", -0.6931471805599453)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tonight",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = -1.3962446919730587, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -0.28438717655492834,
                               unseen = -4.356708826689592,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 76}}),
       ("<time-of-day> o'clock",
        Classifier{okData =
                     ClassData{prior = -0.5714502455824255, unseen = -4.59511985013459,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 48},
                   koData =
                     ClassData{prior = -0.831733343846092, unseen = -4.343805421853684,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 37}}),
       ("number suffix: \21313",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.7376696182833684,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 40},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20803\26086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.1232926914673531, unseen = -7.333676395657684,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -5.723585101952381),
                                    ("dayhour", -2.1797314198887023),
                                    ("last last year<named-month> <day-of-month>",
                                     -6.639875833826536),
                                    ("daymonth", -5.253581472706645),
                                    ("<named-month> <day-of-month><part-of-day> <dim time>",
                                     -4.11414718951828),
                                    ("monthday", -2.5455312716044354),
                                    ("this yearmonth (numeric with month symbol)",
                                     -6.234410725718371),
                                    ("yearhour", -3.362731100834359),
                                    ("this <cycle><named-month> <day-of-month>",
                                     -6.234410725718371),
                                    ("<day-of-month>noon", -6.639875833826536),
                                    ("<dim time> <part-of-day>half after|past <integer> (hour-of-day)",
                                     -6.234410725718371),
                                    ("this <cycle>month (numeric with month symbol)",
                                     -6.234410725718371),
                                    ("todayrelative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -5.723585101952381),
                                    ("last last yearintersect", -4.768073656924945),
                                    ("intersect by \",\"<day-of-month>", -4.624972813284271),
                                    ("next yearintersect", -4.768073656924945),
                                    ("<dim time> <part-of-day>quarter after|past <integer> (hour-of-day)",
                                     -6.234410725718371),
                                    ("<day-of-month><time-of-day> o'clock", -4.288500576663058),
                                    ("year (numeric with year symbol)<named-month> <day-of-month>",
                                     -4.499809670330265),
                                    ("<dim time> <part-of-day><time-of-day> o'clock",
                                     -3.3256898291540105),
                                    ("<day-of-month><part-of-day> <dim time>", -3.965727184400007),
                                    ("monthhour", -2.6790626642289577),
                                    ("last last year<dim time> <part-of-day>", -6.234410725718371),
                                    ("year (numeric with year symbol)month (numeric with month symbol)",
                                     -4.624972813284271),
                                    ("dayday", -3.289971746551931),
                                    ("todayrelative minutes after|past <integer> (hour-of-day)",
                                     -5.387112865331168),
                                    ("hourhour", -2.822163507869631),
                                    ("this <cycle><day-of-month>", -6.234410725718371),
                                    ("this <cycle><part-of-day> <dim time>", -5.135798437050262),
                                    ("<named-month> <day-of-month>noon", -6.639875833826536),
                                    ("last yearmonth (numeric with month symbol)",
                                     -6.639875833826536),
                                    ("this <time><time-of-day> o'clock", -5.723585101952381),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day)",
                                     -5.387112865331168),
                                    ("<dim time> <part-of-day>three quarter after|past <integer> (hour-of-day)",
                                     -6.234410725718371),
                                    ("this <cycle><time-of-day> o'clock", -6.234410725718371),
                                    ("last year<named-month> <day-of-month>", -6.639875833826536),
                                    ("the day after the day after tomorrow<part-of-day> <dim time>",
                                     -5.723585101952381),
                                    ("hourminute", -4.499809670330265),
                                    ("next yearmonth (numeric with month symbol)",
                                     -6.639875833826536),
                                    ("absorption of , after named daymonth (numeric with month symbol)",
                                     -5.253581472706645),
                                    ("next next yearmonth (numeric with month symbol)",
                                     -6.639875833826536),
                                    ("month (numeric with month symbol)<day-of-month>",
                                     -2.7897282321164774),
                                    ("<named-month> <day-of-month><time-of-day> o'clock",
                                     -4.388584035220041),
                                    ("<dim time> <part-of-day>relative minutes to|till|before <integer> (hour-of-day)",
                                     -6.234410725718371),
                                    ("month (numeric with month symbol)<dim time> <part-of-day>",
                                     -3.8066624897703196),
                                    ("next next year<named-month> <day-of-month>",
                                     -6.639875833826536),
                                    ("absorption of , after named day<named-month> <day-of-month>",
                                     -4.624972813284271),
                                    ("this yearintersect", -6.234410725718371),
                                    ("next year<dim time> <part-of-day>", -6.234410725718371),
                                    ("intersect<time-of-day> o'clock", -3.4828754126764228),
                                    ("yearmonth", -4.1975287984573315),
                                    ("intersect<dim time> <part-of-day>", -5.723585101952381),
                                    ("this year<named-month> <day-of-month>", -6.234410725718371),
                                    ("next next yearintersect", -4.768073656924945),
                                    ("intersect<day-of-month>", -3.669461368256835),
                                    ("dayminute", -3.669461368256835),
                                    ("intersect<part-of-day> <dim time>", -3.4412027162758547),
                                    ("last year<dim time> <part-of-day>", -6.234410725718371),
                                    ("todayhalf after|past <integer> (hour-of-day)",
                                     -6.639875833826536),
                                    ("absorption of , after named dayintersect",
                                     -4.624972813284271),
                                    ("today<time-of-day> o'clock", -6.234410725718371),
                                    ("intersectnoon", -6.639875833826536),
                                    ("tonight<time-of-day> o'clock", -5.723585101952381),
                                    ("last yearintersect", -4.768073656924945),
                                    ("next next year<dim time> <part-of-day>", -6.234410725718371),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -5.135798437050262),
                                    ("intersectintersect", -4.768073656924945),
                                    ("today<part-of-day> <dim time>", -5.135798437050262),
                                    ("the day after the day after tomorrow<time-of-day> o'clock",
                                     -6.639875833826536),
                                    ("year (numeric with year symbol)intersect",
                                     -4.499809670330265),
                                    ("yearday", -3.4412027162758547),
                                    ("next year<named-month> <day-of-month>", -6.639875833826536),
                                    ("month (numeric with month symbol)intersect",
                                     -3.307671323651332),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -5.723585101952381),
                                    ("this <cycle>half after|past <integer> (hour-of-day)",
                                     -6.639875833826536),
                                    ("this <cycle>intersect", -6.234410725718371),
                                    ("last last yearmonth (numeric with month symbol)",
                                     -6.639875833826536)],
                               n = 724},
                   koData =
                     ClassData{prior = -2.1542071922525285, unseen = -5.60947179518496,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -3.4085774889597777),
                                    ("dayhour", -1.6739764335716716),
                                    ("monthday", -4.912654885736052),
                                    ("the day after tomorrow<part-of-day> <dim time>",
                                     -3.996364153861897),
                                    ("month (numeric with month symbol)next n <cycle>",
                                     -4.912654885736052),
                                    ("<day-of-month><time-of-day> o'clock", -3.8140425970679424),
                                    ("<dim time> <part-of-day><time-of-day> o'clock",
                                     -2.772588722239781),
                                    ("todayrelative minutes after|past <integer> (hour-of-day)",
                                     -3.8140425970679424),
                                    ("hourhour", -2.772588722239781),
                                    ("this <cycle><part-of-day> <dim time>", -2.8977518651937872),
                                    ("this <cycle>relative minutes after|past <integer> (hour-of-day)",
                                     -3.8140425970679424),
                                    ("this <cycle><dim time> <part-of-day>", -4.507189777627888),
                                    ("this <cycle><time-of-day> o'clock", -3.659891917240684),
                                    ("hourminute", -3.4085774889597777),
                                    ("weekhour", -4.507189777627888),
                                    ("dayminute", -2.661363087129557),
                                    ("the day after tomorrow<time-of-day> o'clock",
                                     -4.912654885736052),
                                    ("today<time-of-day> o'clock", -3.659891917240684),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -3.4085774889597777),
                                    ("today<part-of-day> <dim time>", -2.8977518651937872)],
                               n = 95}}),
       ("half after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("early morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 14},
                   koData =
                     ClassData{prior = -0.6931471805599453, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 14}}),
       ("Saturday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.7472144018302211,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("month (grain)", -1.791759469228055),
                                    ("year (grain)", -2.4849066497880004),
                                    ("week (grain)", -1.3862943611198906),
                                    ("year", -2.4849066497880004), ("month", -1.791759469228055)],
                               n = 9},
                   koData =
                     ClassData{prior = -0.6418538861723948, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.8602012652231115),
                                    ("week (grain)", -0.8602012652231115)],
                               n = 10}}),
       ("last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.0943445622221,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.9980959022258835),
                                    ("Monday", -1.9980959022258835), ("Friday", -2.691243082785829),
                                    ("day", -0.7453329337305155), ("Tuesday", -1.6796421711073488)],
                               n = 27},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes after|past <integer> (hour-of-day) with minute unit",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -2.4849066497880004),
                                    ("<integer> (latent time-of-day)integer with consecutive unit modifiers",
                                     -1.2321436812926323),
                                    ("<integer> (latent time-of-day)integer (numeric)",
                                     -1.791759469228055),
                                    ("hour", -0.7801585575495751)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd/yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening|night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.258096538021482,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 24},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day before the day before yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes to|till|before <integer> (hour-of-day) with minute unit reversed",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)<integer> (latent time-of-day)",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm (time-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> (latent time-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.4656336295746172, unseen = -4.51085950651685,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.5679840376059393),
                                    ("integer with consecutive unit modifiers",
                                     -3.4011973816621555),
                                    ("integer (0..10)", -0.9444616088408514)],
                               n = 86},
                   koData =
                     ClassData{prior = -0.9881552931037991, unseen = -4.02535169073515,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -2.3978952727983707),
                                    ("integer (0..10)", -0.29376111852816306),
                                    ("<number>\20010/\20491", -1.927891643552635)],
                               n = 51}}),
       ("nth <time> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -0.6931471805599453),
                                    ("month (numeric with month symbol)ordinal (digits)Monday",
                                     -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (numeric with month symbol)",
        Classifier{okData =
                     ClassData{prior = -0.19268434382950125,
                               unseen = -4.442651256490317,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8198988861990892),
                                    ("number suffix: \21313", -2.8213788864092133),
                                    ("integer (0..10)", -0.7172447321390059)],
                               n = 80},
                   koData =
                     ClassData{prior = -1.7414976344471669,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (0..10)", -1.9459101490553135),
                                    ("<number>\20010/\20491", -0.2719337154836418)],
                               n = 17}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = -0.9108706644048158,
                               unseen = -3.6635616461296463,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 37},
                   koData =
                     ClassData{prior = -0.5144553918165694, unseen = -4.04305126783455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 55}}),
       ("year (numeric with year symbol)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 14},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24858\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day after the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, negative or minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 4}}),
       ("Friday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("three quarter after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\28595\38376\22238\24402\32426\24565\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("fractional number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5}}),
       ("Sunday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("afternoon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> from now",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.5908683314395271, unseen = -4.394449154672439,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.8971199848858813),
                                    ("month (grain)", -3.283414346005772),
                                    ("year (grain)", -2.5902671654458267),
                                    ("week (grain)", -1.8971199848858813),
                                    ("day", -1.4375876555074412), ("year", -2.5902671654458267),
                                    ("month", -3.283414346005772),
                                    ("day (grain)", -1.4375876555074412)],
                               n = 36},
                   koData =
                     ClassData{prior = -0.807091439909163, unseen = -4.204692619390966,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.7884573603642702),
                                    ("week (grain)", -0.7884573603642702)],
                               n = 29}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -0.48550781578170077,
                               unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16},
                   koData =
                     ClassData{prior = -0.9555114450274363,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10}}),
       ("<dim time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -9.806121317621475e-2,
                               unseen = -5.910796644040527,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.7960951498123877),
                                    ("this <time>early morning", -5.214935757608986),
                                    ("<day-of-month>evening|night", -3.6054978451748854),
                                    ("<day-of-month>early morning", -4.116323468940876),
                                    ("the day after the day after tomorrowafternoon",
                                     -5.214935757608986),
                                    ("<named-month> <day-of-month>morning", -2.863560500445508),
                                    ("Fridayafternoon", -4.809470649500821),
                                    ("<named-month> <day-of-month>evening|night",
                                     -3.9621727891136174),
                                    ("intersectafternoon", -4.298645025734831),
                                    ("this <time>evening|night", -5.214935757608986),
                                    ("\24773\20154\33410evening|night", -4.809470649500821),
                                    ("<day-of-month>morning", -2.772588722239781),
                                    ("this <day-of-week>afternoon", -5.214935757608986),
                                    ("Fridayearly morning", -4.809470649500821),
                                    ("Fridaymorning", -4.809470649500821),
                                    ("the day after the day after tomorrowmorning",
                                     -4.809470649500821),
                                    ("\20799\31461\33410afternoon", -4.809470649500821),
                                    ("<named-month> <day-of-month>afternoon", -4.298645025734831),
                                    ("this <cycle>morning", -3.828641396489095),
                                    ("todayearly morning", -5.214935757608986),
                                    ("intersectevening|night", -3.9621727891136174),
                                    ("this <day-of-week>evening|night", -5.214935757608986),
                                    ("this <time>afternoon", -5.214935757608986),
                                    ("this <day-of-week>early morning", -5.214935757608986),
                                    ("intersectearly morning", -4.5217885770490405),
                                    ("intersectmorning", -2.4115753767024506),
                                    ("<day-of-month>afternoon", -3.9621727891136174),
                                    ("Mondaymorning", -3.7108583608327117),
                                    ("<named-month> <day-of-month>early morning",
                                     -4.5217885770490405),
                                    ("this <cycle>early morning", -5.214935757608986),
                                    ("todaymorning", -3.828641396489095),
                                    ("Fridayevening|night", -4.809470649500821)],
                               n = 165},
                   koData =
                     ClassData{prior = -2.3707933430205794, unseen = -4.290459441148391,
                               likelihoods =
                                 HashMap.fromList
                                   [("the day after tomorrowafternoon", -3.58351893845611),
                                    ("dayhour", -1.791759469228055),
                                    ("<integer> (latent time-of-day)afternoon",
                                     -3.1780538303479458),
                                    ("<day-of-month>evening|night", -3.58351893845611),
                                    ("<day-of-month>early morning", -3.58351893845611),
                                    ("hourhour", -2.330755969960742),
                                    ("<integer> (latent time-of-day)early morning",
                                     -3.1780538303479458),
                                    ("the day after tomorrowmorning", -3.1780538303479458),
                                    ("<day-of-month>morning", -2.4849066497880004),
                                    ("<integer> (latent time-of-day)morning", -3.1780538303479458),
                                    ("<day-of-month>afternoon", -3.58351893845611)],
                               n = 17}}),
       ("<part-of-day> <dim time>",
        Classifier{okData =
                     ClassData{prior = -0.5017962170465965, unseen = -5.293304824724492,
                               likelihoods =
                                 HashMap.fromList
                                   [("tonight<integer> (latent time-of-day)", -3.6788291182604347),
                                    ("morning<time-of-day> o'clock", -2.890371757896165),
                                    ("evening|night<time-of-day> o'clock", -3.0910424533583156),
                                    ("morning<integer> (latent time-of-day)", -2.890371757896165),
                                    ("morningrelative minutes to|till|before <integer> (hour-of-day)",
                                     -4.59511985013459),
                                    ("hourhour", -1.177393166521224),
                                    ("morningrelative minutes after|past <integer> (hour-of-day) with minute unit",
                                     -3.9019726695746444),
                                    ("morninghalf after|past <integer> (hour-of-day)",
                                     -4.189654742026425),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -2.890371757896165),
                                    ("evening|night<integer> (latent time-of-day)",
                                     -3.0910424533583156),
                                    ("afternoon<time-of-day> o'clock", -3.2088254890146994),
                                    ("hourminute", -1.8870696490323797),
                                    ("morningquarter after|past <integer> (hour-of-day)",
                                     -4.189654742026425),
                                    ("afternoon<integer> (latent time-of-day)",
                                     -3.2088254890146994),
                                    ("early morning<time-of-day> o'clock", -4.59511985013459),
                                    ("afternoonhh:mm (time-of-day)", -4.59511985013459),
                                    ("morningthree quarter after|past <integer> (hour-of-day)",
                                     -4.189654742026425),
                                    ("tonight<time-of-day> o'clock", -3.6788291182604347),
                                    ("early morning<integer> (latent time-of-day)",
                                     -4.59511985013459),
                                    ("morningrelative minutes after|past <integer> (hour-of-day)",
                                     -3.0910424533583156)],
                               n = 89},
                   koData =
                     ClassData{prior = -0.9299895762323169, unseen = -4.919980925828125,
                               likelihoods =
                                 HashMap.fromList
                                   [("morning<time-of-day> o'clock", -2.204604684633842),
                                    ("morning<integer> (latent time-of-day)", -2.204604684633842),
                                    ("hourhour", -1.2237754316221157),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -2.5147596129376812),
                                    ("afternoon<time-of-day> o'clock", -3.120895416507997),
                                    ("hourminute", -1.916922612182061),
                                    ("afternoon<integer> (latent time-of-day)", -2.966744736680739),
                                    ("morningrelative minutes after|past <integer> (hour-of-day)",
                                     -2.6100697927420065)],
                               n = 58}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -6.289715570908998,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.068982735293584),
                                    ("integer (0..10)month (grain)", -2.526658444468222),
                                    ("integer (0..10)hour (grain)", -3.4546452161055683),
                                    ("<number>\20010/\20491week (grain)", -3.889963287363414),
                                    ("integer (numeric)day (grain)", -3.6488012305465256),
                                    ("compose by multiplicationminute (grain)", -5.594711379601839),
                                    ("second", -3.6488012305465256),
                                    ("integer (0..10)day (grain)", -3.2433361224383614),
                                    ("number suffix: \21313month (grain)", -4.678420647727684),
                                    ("integer (0..10)year (grain)", -3.9852734671677386),
                                    ("<number>\20010/\20491month (grain)", -3.5152698379220033),
                                    ("number suffix: \21313minute (grain)", -5.594711379601839),
                                    ("integer (numeric)year (grain)", -3.5798083590595744),
                                    ("integer (0..10)second (grain)", -3.6488012305465256),
                                    ("day", -2.550188941878416),
                                    ("integer with consecutive unit modifiersday (grain)",
                                     -4.090633982825565),
                                    ("year", -3.1098047298138387),
                                    ("integer (0..10)minute (grain)", -3.1968161068034684),
                                    ("hour", -3.2433361224383614),
                                    ("integer (0..10)week (grain)", -3.5798083590595744),
                                    ("month", -1.7028910814912124),
                                    ("integer (numeric)minute (grain)", -4.496099090933729),
                                    ("<number>\20010/\20491hour (grain)", -4.678420647727684),
                                    ("integer (numeric)month (grain)", -2.67694064751756),
                                    ("integer with consecutive unit modifiersminute (grain)",
                                     -3.889963287363414),
                                    ("minute", -2.624296914032138)],
                               n = 256}}),
       ("last last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> am|pm",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mm (time-of-day)", -1.252762968495368),
                                    ("<integer> (latent time-of-day)", -1.540445040947149),
                                    ("hour", -1.540445040947149), ("minute", -1.252762968495368)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 3}}),
       ("<day-of-month>",
        Classifier{okData =
                     ClassData{prior = -0.17768117723745236,
                               unseen = -4.727387818712341,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.8064758658669484),
                                    ("number suffix: \21313", -2.639057329615259),
                                    ("integer with consecutive unit modifiers",
                                     -1.1631508098056809),
                                    ("integer (0..10)", -1.7740598921286541)],
                               n = 108},
                   koData =
                     ClassData{prior = -1.8152899666382492, unseen = -3.258096538021482,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)", -0.12783337150988489)],
                               n = 21}}),
       ("number suffix: \19975",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("relative minutes after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.640037355245997, unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -3.0602707946915624),
                                    ("<integer> (latent time-of-day)integer with consecutive unit modifiers",
                                     -1.3256697393034558),
                                    ("<integer> (latent time-of-day)integer (numeric)",
                                     -1.6739764335716716),
                                    ("hour", -0.7576857016975165)],
                               n = 29},
                   koData =
                     ClassData{prior = -0.7492366472109889, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)compose by multiplication",
                                     -2.9618307218783095),
                                    ("<integer> (latent time-of-day)number suffix: \21313",
                                     -1.9810014688665833),
                                    ("<integer> (latent time-of-day)integer (0..10)",
                                     -1.1700712526502546),
                                    ("hour", -0.7646061445420903)],
                               n = 26}}),
       ("intersect by \",\"",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.330733340286331,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -2.2380465718564744),
                                    ("Sunday<named-month> <day-of-month>", -1.6094379124341003),
                                    ("Sundaymonth (numeric with month symbol)",
                                     -2.2380465718564744),
                                    ("dayday", -0.9501922835498364),
                                    ("Sundayintersect", -1.6094379124341003)],
                               n = 35},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer with consecutive unit modifiers",
        Classifier{okData =
                     ClassData{prior = -7.410797215372185e-2,
                               unseen = -4.02535169073515,
                               likelihoods =
                                 HashMap.fromList
                                   [("number suffix: \21313integer (0..10)", -0.7492366472109889),
                                    ("compose by multiplicationinteger (0..10)",
                                     -2.908720896564361),
                                    ("integer (0..10)integer (0..10)", -0.7492366472109889)],
                               n = 52},
                   koData =
                     ClassData{prior = -2.639057329615259, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("number suffix: \21313integer (0..10)", -0.8472978603872037),
                                    ("integer (0..10)integer (0..10)", -0.8472978603872037)],
                               n = 4}}),
       ("second (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("\22307\35806\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -1.3217558399823195,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.9007865453381898), ("Sunday", -1.3862943611198906),
                                    ("Tuesday", -1.6739764335716716)],
                               n = 12},
                   koData =
                     ClassData{prior = -0.3101549283038396, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> o'clock", -3.20545280453606),
                                    ("<integer> (latent time-of-day)", -0.9718605830289657),
                                    ("month (numeric with month symbol)", -2.6946271807700692),
                                    ("hour", -0.9028677115420143), ("month", -2.6946271807700692)],
                               n = 33}}),
       ("the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = -1.2039728043259361,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("\22919\22899\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("noon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -0.9555114450274363, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.5040773967762742),
                                    ("day", -0.8979415932059586), ("Tuesday", -1.5040773967762742)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.48550781578170077,
                               unseen = -3.6888794541139363,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.8909729238898653),
                                    ("month (numeric with month symbol)", -2.9704144655697013),
                                    ("hour", -0.8909729238898653), ("month", -2.9704144655697013)],
                               n = 16}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.8472978603872037,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("month (grain)", -1.791759469228055),
                                    ("year (grain)", -2.4849066497880004),
                                    ("week (grain)", -1.3862943611198906),
                                    ("year", -2.4849066497880004), ("month", -1.791759469228055)],
                               n = 9},
                   koData =
                     ClassData{prior = -0.5596157879354228,
                               unseen = -3.4339872044851463,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.8362480242006186),
                                    ("week (grain)", -0.8362480242006186)],
                               n = 12}}),
       ("next n <cycle>",
        Classifier{okData =
                     ClassData{prior = -2.353049741019416e-2,
                               unseen = -4.624972813284271,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.41789593950504),
                                    ("integer (0..10)hour (grain)", -2.6692103677859462),
                                    ("<number>\20010/\20491week (grain)", -3.005682604407159),
                                    ("second", -2.8233610476132043),
                                    ("integer (0..10)day (grain)", -2.5356789751614235),
                                    ("integer (0..10)year (grain)", -3.228826155721369),
                                    ("<number>\20010/\20491month (grain)", -2.8233610476132043),
                                    ("integer (0..10)second (grain)", -2.8233610476132043),
                                    ("day", -2.5356789751614235), ("year", -3.228826155721369),
                                    ("integer (0..10)minute (grain)", -2.6692103677859462),
                                    ("hour", -2.41789593950504),
                                    ("integer (0..10)week (grain)", -3.005682604407159),
                                    ("month", -2.8233610476132043),
                                    ("<number>\20010/\20491hour (grain)", -3.5165082281731497),
                                    ("minute", -2.6692103677859462)],
                               n = 42},
                   koData =
                     ClassData{prior = -3.7612001156935624, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)day (grain)", -2.2512917986064953),
                                    ("day", -2.2512917986064953)],
                               n = 1}}),
       ("\19975\22307\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20799\31461\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Tuesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-month> <day-of-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -5.2574953720277815,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (numeric with month symbol)integer with consecutive unit modifiers",
                                     -1.6969253665572162),
                                    ("month (numeric with month symbol)integer (numeric)",
                                     -1.6969253665572162),
                                    ("month (numeric with month symbol)number suffix: \21313",
                                     -3.1728318863667937),
                                    ("month", -0.708978645776626),
                                    ("month (numeric with month symbol)integer (0..10)",
                                     -2.3078344488801896)],
                               n = 93},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\21171\21160\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (0..10)",
        Classifier{okData =
                     ClassData{prior = -0.3656191995609647, unseen = -5.552959584921617,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 256},
                   koData =
                     ClassData{prior = -1.1834088253281867, unseen = -4.74493212836325,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 113}}),
       ("last n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.605170185988091,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.9856819377004897),
                                    ("integer (0..10)month (grain)", -3.4965075614664802),
                                    ("integer (0..10)hour (grain)", -2.3978952727983707),
                                    ("second", -2.649209701079277),
                                    ("integer (0..10)day (grain)", -2.9856819377004897),
                                    ("integer (0..10)year (grain)", -3.4965075614664802),
                                    ("<number>\20010/\20491month (grain)", -2.3978952727983707),
                                    ("integer (0..10)second (grain)", -2.649209701079277),
                                    ("day", -2.9856819377004897), ("year", -3.4965075614664802),
                                    ("integer (0..10)minute (grain)", -2.3978952727983707),
                                    ("hour", -2.3978952727983707),
                                    ("integer (0..10)week (grain)", -2.9856819377004897),
                                    ("month", -2.1972245773362196),
                                    ("minute", -2.3978952727983707)],
                               n = 42},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("<number>\20010/\20491", -0.1823215567939546)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)", -0.1823215567939546)],
                               n = 4}}),
       ("n <cycle> last",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.04305126783455,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.4159137783010487),
                                    ("integer (0..10)hour (grain)", -2.9267394020670396),
                                    ("<number>\20010/\20491week (grain)", -2.9267394020670396),
                                    ("second", -2.9267394020670396),
                                    ("integer (0..10)day (grain)", -2.4159137783010487),
                                    ("integer (0..10)year (grain)", -2.9267394020670396),
                                    ("<number>\20010/\20491month (grain)", -2.9267394020670396),
                                    ("integer (0..10)second (grain)", -2.9267394020670396),
                                    ("day", -2.4159137783010487), ("year", -2.9267394020670396),
                                    ("integer (0..10)minute (grain)", -2.9267394020670396),
                                    ("hour", -2.4159137783010487),
                                    ("integer (0..10)week (grain)", -2.9267394020670396),
                                    ("month", -2.9267394020670396),
                                    ("<number>\20010/\20491hour (grain)", -2.9267394020670396),
                                    ("minute", -2.9267394020670396)],
                               n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.871201010907891,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 46},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("relative minutes to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (numeric)",
                                     -0.8472978603872037),
                                    ("hour", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer (0..10)",
                                     -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 1}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -0.4353180712578455,
                               unseen = -3.5553480614894135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 33},
                   koData =
                     ClassData{prior = -1.041453874828161, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18}}),
       ("<number>\20010/\20491",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4339872044851463,
                               likelihoods = HashMap.fromList [("integer (0..10)", 0.0)], n = 29},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("compose by multiplication",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)number suffix: \21313", 0.0)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24773\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("nth <time> of <time> 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -0.6931471805599453),
                                    ("month (numeric with month symbol)ordinal (digits)Monday",
                                     -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.59511985013459,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.505525936990736),
                                    ("evening|night", -2.9755295662364714),
                                    ("Monday", -2.505525936990736), ("Friday", -3.1986731175506815),
                                    ("day", -1.252762968495368),
                                    ("<dim time> <part-of-day>", -3.1986731175506815),
                                    ("<part-of-day> <dim time>", -2.3877429013343523),
                                    ("hour", -1.6945957207744071), ("Tuesday", -2.187072205872201),
                                    ("week-end", -3.4863551900024623)],
                               n = 44},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [], n = 0}})]